### ISSUE TITLE
Attributes with parameters

### ISSUE THREAD

**Issue by Juanjdurillo** [jMetal/jMetal#103]
Hi, here I come again with a basic design question (I hope not to get on anyone nerves, since it is related to a similar problem I had in the issue #100)

I need to include a new Ranking which will be computed based on a set of values. These values are provided in a file, and can be different for different problems. That computed ranking should be of course an attribute of solution. I have designed my new `R2Ranking` class as follows: 

``` java
public class R2Ranking<S extends Solution<?>>  implements Ranking<S>{
public R2Ranking(File file) {
        // extract parameters from the file
    }
```

I have passed the file in the constructor because such a ranking does not makes sense without that information. This way, I force/remind ~~call it whatever you want~~ the user of this class to always provide this information. I know I can provide that information in another way, like providing a method called `setParameterFile`. However, I am not conviced of this latter approach since then I am forcing the user to a given protocol (calling the setParameter for each parameter she needs to provide, before calling the `computingRanking` method), which will not detect in Compiling time she hasn't provided the required parameters (if the constructor requires the File, then the user in Compiling time is aware of it). Of course here one can always say: the user can still provide `null`: yeah, OK. 

As `Ranking` in jMetal also extends `GenericSolutionAttribute` then `R2Ranking` is also an Attribute.

So far, so good. My ranking is computing the right things. The problem appears now when I want to use the attribute computed by R2Ranking in an algorithm. What I have seen so far is that attributes are retrieved in jMetal in the following way (those are examples in the code):
1. In the `RankingComparator`, for the `NonDominanceRanking`

``` java
private Ranking<S> ranking = new DominanceRanking<S>() ;
rank1 = (int) ranking.getAttribute(solution1);
```
1. In the `CrowdingDistanceComparator`, for the `CrowdingDistance`

``` java
private final CrowdingDistance<S> crowdingDistance = new CrowdingDistance<S>() ;
distance2 = (double) crowdingDistance.getAttribute(solution2);
```

OK, so why not doing the same for the new `R2Ranking`? Well, because I do not want to provide an empty constructor (at least a public one). If `R2Ranking` has a public empty constructor, anyone can create instances of such `R2Ranking` without specifiy a file and then call the computeRanking method without specifying the parameters as said before. At the same time, I do not want to instantiate a `R2Ranking` providing the File, because the algorithm in which I am using it does not need to know about that File. 

What is the best alternative for my problem? I am sure is again that I have a misconception of something (my other though is that attributes should be rethough in jMetal).

**Comment by matthieu-vergne** [comment]
> I hope not to get on anyone nerves

I guess I am the one targeted here. Don't mind about my nerves, when you are a perfectionist you are just picky on stuff that others don't care about. Take my "anger" as a feature. {^_°}

> I need to include a new Ranking which will be computed based on a set of values. These values are provided in a file, and can be different for different problems.

I see two things here:
- a specific type of ranking *processing*, which is based on a set of values
- a specific type or ranking *management*, which is based on a (problem-specific) file

So basically, I would see two implementations here:
- a generic class which focus on the processing, probably your current `R2Ranking` but which takes the set of values (`Set`, or several arguments, or maybe a `Map`, whatever),
- a file-based class which extends the generic one, take a file, extract the values, and provide them to the generic (through the constructor, a setter, whatever)

>I do not want to provide an empty constructor (at least a public one). If R2Ranking has a public empty constructor, anyone can create instances of such R2Ranking without specifiy a file and then call the computeRanking method without specifying the parameters

Considering that this information needs to be there before doing any computation, for me it makes sense to have it from the constructor.

> I do not want to instantiate a R2Ranking providing the File, because the algorithm in which I am using it does not need to know about that File. 

Surely, if it is a problem-specific file, the algorithm should not know about it. At least for me, but probably for Antonio it would not be the case, because looking at older discussions he considers that an algorithm aims at solving a given problem, so it should depend on it and know the details. I think that it relates to an issue spotted a while ago about the dependency between algorithms and problems (issue #55), which is still a pending discussion.

So for instance, what we could imagine is that the algorithm request a ranking implementation as a parameter (an instance of the generic class or more generic), and the problem provides an instance of the file-based implementation. Then the point is to link the problem-specific instance to the algorithm-specific parameter. But surely we go back to the issue I mentioned above.

**Comment by Juanjdurillo** [comment]
Thanks for the discussion. Not only your nerves ;) . I just want to make as good as possible and my design skills are not the best (just to use nice words) right now; and I was afraid I was pretty much asking hte same as in #100

**Comment by matthieu-vergne** [comment]
Well, there is always subjectivity in "goodness". I am also biased with my own habits of programming in Java, and the fact that I have more experience and a natural facility to explain myself makes it hard to contradict me on that topic. I let you choose the term "expertise" or "influence". {^_°}

Moreover I am an [anarchist](https://en.wikipedia.org/wiki/Anarchism), and more precisely an [epistemological anarchist](https://en.wikipedia.org/wiki/Epistemological_anarchism), and it applies the same to code, so a long as you are convinced that you do it the right way, I (should) have nothing to say (then the ego is another problem {'^.^}~).
