### ISSUE TITLE
Definition and implementation of archives

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#105]
The discusion in issue #100 introduced the question about the `Archive` interface and its subclasses (mainly the `BoundedArchive`).

The last definition of `Archive` in #100 was:

``` java
/**
 * An {@link Archive} is a collection of non-dominated {@link Solution}s. New
 * solutions may be added to an {@link Archive} through its
 * {@link #add(Solution)} method, but if it is dominated by other
 * {@link Solution}s already present in the {@link Archive}, the addition will
 * not happen. At the opposite, if it is not dominated, any {@link Solution} of
 * the {@link Archive} which is dominated by the new {@link Solution} must be
 * removed.
 * 
 * @param <S>
 *            the type of {@link Solution} stored in this {@link Archive}
 */
public interface Archive<S extends Solution<?>> extends Iterable<S> {

    /**
     * This method provides the {@link Comparator} used to evaluate the
     * dominance of the {@link Solution}s. A {@link Solution} <code>a</code> is
     * dominated by a {@link Solution} <code>b</code> when
     * <code>comparator.compares(a, b) &lt; 0</code> (i.e. a &lt; b).
     * 
     * @return the dominance {@link Comparator}
     */
    public Comparator<S> getDominationComparator();

    /**
     * This method adds a {@link Solution} to this {@link Archive}. Upon
     * addition, the {@link Archive} is cleaned in order to contain only
     * non-dominated {@link Solution}s. The {@link Solution}s removed are
     * returned as a result.<br/>
     * <br/>
     * Depending on the implementation, it may be that dominated
     * {@link Solution}s are also removed, for instance if duplicates are
     * removed or if the {@link Archive} is limited in size. The only constraint
     * is that, after calling {@link #add(Solution)}, only non-dominated
     * {@link Solution}s remain in the {@link Archive}.
     * 
     * @param solution
     *            the {@link Solution} to add
     * @return the dominated {@link Solution}s which has been removed
     */
    public Collection<S> add(S solution);

    /**
     * This {@link Iterator} provides each {@link Solution} contained in this
     * {@link Archive} in an arbitrary order. If the {@link Archive} stores
     * several instances of the same {@link Solution}, all of them should be
     * provided by this {@link Iterator}.
     */
    @Override
    public Iterator<S> iterator();
}
```

Some matters to think about:
## Extending `Iterator<S>`

Would have sense to not extend `Iterator<S>` and replace the `public Iterator<S> iterator();` method by `public Collection<S> getArchivedSolutions()`?
## Bounded archives

As an archive can have a maximum size that is determined when creating the archive, i.e, an unbounded archive is not going to be bounded at runtime, is the current `BoundedArchive` interface the best approach?:

``` java
public interface BoundedArchive<S extends Solution<?>> extends Archive<S> {
  public int getMaxSize() ;
}
```
## The `NondominatedSolutionListArchive` class

jMetal 5 provides a [`NondominatedSolutionListArchive` class](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/archive/impl/NonDominatedSolutionListArchive.java). 

If we take a look to this class, it implements directly the `Archive` interface: a unbounded collection having non-dominated solutions. So the name of this class is somehow redundant, because it is in fact the same that one would expect from a class named `ArchiveImpl` or similar.
## The `AbstractBoundeArchive`

When reviewing the provided archives in jMetal 5, I was surprised when I saw the [`AbstractBoundeArchive` class](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/archive/impl/AbstractBoundedArchive.java):

``` java
public abstract class AbstractBoundedArchive<S extends Solution<?>> implements BoundedArchive<S> {
    protected NonDominatedSolutionListArchive<S> list;
    protected int maxSize;

    public AbstractBoundedArchive(int maxSize) {
        this.maxSize = maxSize;
        this.list = new NonDominatedSolutionListArchive<S>();
    }

    @Override
    public boolean add(S solution) {
        boolean success = list.add(solution);
        if (success)
            prune();

        return success;
    }

    @Override
    public S get(int index) {
        return getSolutionList().get(index);
    }

    @Override
    public List<S> getSolutionList() {
        return list.getSolutionList();
    }

    @Override
    public int size() {
        return list.size();
    }

    @Override
    public int getMaxSize() {
        return maxSize;
    }

    public abstract void prune();
}
```

and the surprise was to be aware that it implements `BoundedArchive<S>` but at the same time it contains a `NonDominatedSolutionListArchive<S>`. 

It's clear that there room for improvement here.

**Comment by matthieu-vergne** [comment]
> Would have sense to not extend `Iterator<S>` and replace the `public Iterator<S> iterator();` method by `public Collection<S> getArchivedSolutions()`?

I don't think so, in the sense that you then inforce the solutions to be provided through a `Collection`, which is more restricted than an `Iterable<S>`. In particular, if you have such a method returning a collection, then you can implement `Iterable<S>`:
```java
public Iterator<S> iterator() {
	return getArchivedSolutions().iterator();
}
```

So if you have the second method, then there is no difficulty in having the first. But because the second one provides a more restricted type, then you are reducing the different `Iterable` implementations one may use. So I think it does not make sense to replace the first by the second. By the way, you should not forget that a `Collection` provides an `add()` method is not supposed to be compatible with the `Archive` one, so if the user get the `Collection` and add to this one, we may have unexpected behaviours. So I think it is better to not do it.

> As an archive can have a maximum size that is determined when creating the archive, i.e, an unbounded archive is not going to be bounded at runtime, is the current `BoundedArchive` interface the best approach?

I may develop a while to explain why interfaces should be used only as root ones, and no extension should be made (so only `Archive` should be an interface). From my point of view, a bounded archive should be a specific implementation which enforces the respect of a size limit, not a mere interface saying that there is such a limit.

> jMetal 5 provides a NondominatedSolutionListArchive class.
> 
> If we take a look to this class, it implements directly the Archive interface: a unbounded collection having non-dominated solutions. So the name of this class is somehow redundant, because it is in fact the same that one would expect from a class named ArchiveImpl or similar.

You may call it simply `SetArchive`, because although it is backed by a `List`, you actually enforce the unicity like a `Set`. By the way, using a `LinkedList` rather than an `ArrayList` would make it (a lot) more performant, because you only use the iterator and you may add stuff at the end and remove stuff in the middle.

> When reviewing the provided archives in jMetal 5, I was surprised when I saw the `AbstractBoundeArchive` class:
> [...]
> and the surprise was to be aware that it implements `BoundedArchive<S>` but at the same time it contains a `NonDominatedSolutionListArchive<S>`.

Nothing surprising here for me: this is an example of case where you have so much similar stuff that it is more interesting to reuse the same implementation. While extending it would have been a mistake, because you would need to override methods, which means that someone using it as a`NonDominatedSolutionListArchive<S>` would get unexpected behaviours, using an internal instance is actually the usual recommendation for this kind of case. You may optimize it by implementing a more specific code rather than reusing, but if the performance impact is negligible then it does not have more value than a mere preference.

**Comment by ajnebro** [comment]
About this:
> > In my opinion [...] the solution should not be saved but the add method should not return false either
>
>By returning the removed solutions, when you add a solution A:
>
>    if A is not part of the returned collection, then A has been added (whether or not it was already here, there is one more A)
>    if A is part of the returned collection, then A has not been added (whether or not it was already here, there is as much A than before)
>    if B (different from A) is part of the returned collection, then B has been removed (whether or not there is still some Bs, there is one less B)

In the first case, if A is dominated it will not be part of the returned collection because it was not there, unless we define that the solution to be added must also be returned if dominated to comply with the second case. 

Assuming that we do that, to know whether a solution S has been implies to check the returned collection:
```java
Collection<S> deletedSolutions = solutions.add(solution);
if (!deletedSolutions.contains(solution)) {
   ...
}
```
So the current implementation of the collection can have a high impact in performance. I'm going to use a hashset for now.

**Comment by matthieu-vergne** [comment]
> In the first case, if A is dominated it will not be part of the returned collection because it was not there, unless we define that the solution to be added must also be returned if dominated to comply with the second case.

This is how I defined it in my interface:
```
* This method adds a {@link Solution} to this {@link Archive}. Upon
* addition, the {@link Archive} is cleaned in order to contain only
* non-dominated {@link Solution}s. The {@link Solution}s removed are
* returned as a result.<br/>
```

So we add the solution, and then we remove the dominated ones. If the added solution is dominated, then it is removed. It does not mean that it must be implemented by adding and only then removing, but it must be implemented such that it is equivalent to that process.

> Assuming that we do that, to know whether a solution S has been implies to check the returned collection:
> [...]
> So the current implementation of the collection can have a high impact in performance. I'm going to use a hashset for now.

I agree with this process: (i) make it works, (ii) make it right, (iii) make it fast. I heard it is from Knuth, but I never checked. Now, we are on the second step, so I try to help you make it right. And surely the third step should not get priority, otherwise you may just make it wrong.

Whether or not it has a significant impact depends on the implementation, and at the interface level there is no implementation, only rules to apply. So you cannot blame the design of the interface if the specific implementation you use is not optimised for providing what it is supposed to provide. But I am sure that you won't be satisfied if I tell you to let this performance issue for later, so let's dig in it now.

Here are the exhaustive cases, assuming we call the method on a solution A:
- A not added, nothing removed: returns {A}
- A not added, B1-Bn removed: returns {A, B1, ..., Bn}
- A added, nothing removed: returns {}
- A added, B1-Bn removed: returns {B1, ..., Bn}

The first case is when A is dominated. The second case is really improbable, but the definition does not forbid it. Surely, with a basic interpretation it is impossible, because it would mean that A dominates B1-Bn, so they are removed, and yet it is not added too (which could happen because it is already there, but then B1-Bn should be already removed). The third case is when A is neither dominant nor dominated. The fourth case is when A dominates B1-Bn.

Regarding the performances, whatever the implementation, the cases 1 and 3 should be really fast, because there is between 0 and 1 check to do. The problematic cases are the 2 (which is unlikely to happen) and 4. This means that performances may be significantly impacted when we have these B1-Bn solutions. Now, if I consider the code you shown me, I understand that these are your requirements:
- if I ask whether or not A is part of the removed solutions, it should be O(1), so it is like checking a boolean saying whether or not A has been added
- if I ask whether or not any other solution is part of the removed solutions, it should be as quick as possible, typically like a `HashSet`

My recommendation: create a `Collection` which stores an internal `HashSet` for B1-Bn and stores A separately. This implementation is aimed to be used as a result of the `Archive.add()` method, so you may call it `AddResult` and implement it **inside** your `SetArchive` (or whatever you call it), because it takes assumptions based on the archive it is implemented for (like the unicity of the solutions). Or you may call it `SetArchiveAddResult` and implement it **outside** the archive, so it takes its own assumptions. It takes A in its constructor, to know which solution should be stored outside the `HashSet`, and its methods are implemented to make the difference between the two cases. Here is an example:
```java
public class SetArchiveAddResult<S extends Solution<?>> implements
		Collection<S> {

	private final S providedSolution;
	private boolean containsProvided = false;
	private final HashSet<S> otherSolutions = new HashSet<>();

	public SetArchiveAddResult(S providedSolution) {
		this.providedSolution = providedSolution;
	}

	@Override
	public boolean add(S solution) {
		if (solution.equals(providedSolution)) {
			if (containsProvided) {
				return false;
			} else {
				containsProvided = true;
				return true;
			}
		} else {
			return otherSolutions.add(solution);
		}
	}

	@Override
	public boolean addAll(Collection<? extends S> solutions) {
		boolean isModified = false;
		for (S solution : solutions) {
			isModified |= add(solution);
		}
		return isModified;
	}

	@Override
	public boolean remove(Object objet) {
		if (objet.equals(providedSolution)) {
			if (!containsProvided) {
				return false;
			} else {
				containsProvided = false;
				return true;
			}
		} else {
			return otherSolutions.remove(objet);
		}
	}

	@Override
	public boolean removeAll(Collection<?> objects) {
		boolean isModified = false;
		for (Object object : objects) {
			isModified |= remove(object);
		}
		return isModified;
	}

	@Override
	public void clear() {
		containsProvided = false;
		otherSolutions.clear();
	}

	@Override
	public boolean contains(Object o) {
		return o.equals(providedSolution) && containsProvided
				|| !o.equals(providedSolution) && otherSolutions.contains(o);
	}

	@Override
	public boolean containsAll(Collection<?> c) {
		for (Object object : c) {
			if (contains(object)) {
				// check others
			} else {
				return false;
			}
		}
		return true;
	}

	@Override
	public boolean isEmpty() {
		return !containsProvided && otherSolutions.isEmpty();
	}

	@Override
	public Iterator<S> iterator() {
		return new Iterator<S>() {

			private final Iterator<S> othersIterator = otherSolutions
					.iterator();
			private boolean shouldReturnProvided = containsProvided;
			private S lastReturned = null;

			@Override
			public boolean hasNext() {
				return othersIterator.hasNext() || shouldReturnProvided;
			}

			@Override
			public S next() {
				if (shouldReturnProvided) {
					lastReturned = providedSolution;
					shouldReturnProvided = false;
				} else {
					lastReturned = othersIterator.next();
				}
				return lastReturned;
			}

			@Override
			public void remove() {
				SetArchiveAddResult.this.remove(lastReturned);
			}
		};
	}

	@Override
	public boolean retainAll(Collection<?> objects) {
		boolean isModifed = false;

		if (containsProvided && !objects.contains(providedSolution)) {
			containsProvided = false;
			isModifed = true;
		} else {
			// nothing to change for the provided solution
		}

		isModifed |= otherSolutions.retainAll(objects);

		return isModifed;
	}

	@Override
	public int size() {
		int size = otherSolutions.size();
		if (containsProvided) {
			size++;
		} else {
			// correct size
		}
		return size;
	}

	@Override
	public Object[] toArray() {
		Collection<Object> list = new LinkedList<>();
		list.addAll(otherSolutions);
		if (containsProvided) {
			list.add(providedSolution);
		} else {
			// nothing else to add
		}
		return list.toArray();
	}

	@Override
	public <T> T[] toArray(T[] a) {
		Collection<Object> list = new LinkedList<>();
		list.addAll(otherSolutions);
		if (containsProvided) {
			list.add(providedSolution);
		} else {
			// nothing else to add
		}
		return list.toArray(a);
	}
}
```

I did not test it, so maybe there is some stuff to fix, and we may implement the `addAll()` and `removeAll()` in a more optimized way, but the core stuff should be there and it should fulfill your requirements.

But I repeat it: implementation should not take the priority on (interface) design or you may make it wrong. As far as I know, [Java is a universal Turing machine](http://rosettacode.org/wiki/Universal_Turing_machine), so you may implement what you want as long as (i) it is possible for a Turing machine and (ii) you know how to do it in Java. So do not bother much about performance before you have implemented a strong set of tests (for the class of interest) to ensure that you can make all the optimizations you want without facing regression.

**Comment by ajnebro** [comment]
> Here are the exhaustive cases, assuming we call the method on a solution A:
>
>*    A not added, nothing removed: returns {A}
>*    A not added, B1-Bn removed: returns {A, B1, ..., Bn}
>*    A added, nothing removed: returns {}
>*    A added, B1-Bn removed: returns {B1, ..., Bn}
>
> The first case is when A is dominated. The second case is really improbable, but the definition does not forbid it.

The second case is not improbable; on the contrary, I would say that it can be a very common case.

I think that the four cases are correct. I'm going to consider them in the pilot implementation I'm doing in a local branch.

**Comment by ajnebro** [comment]
And I'm going to test the performance of the different alternatives. My impression is that the performance penalty, if any, will be neglibigle.

**Comment by matthieu-vergne** [comment]
> The second case is not improbable; on the contrary, I would say that it can be a very common case.

I don't think so, but it is not the issue so I will not ask an example.

**Comment by ajnebro** [comment]
By the way, this is Málaga Fair week (http://www.andalucia.org/en/malaga-fair/). Please, take that into account if I say some (i.e., more than usual) foolishness ;);););) ... and I have so say that I don't like Malaga Fair but there are other more interesting alternatives ^_°

**Comment by Juanjdurillo** [comment]
The second case is not possible. If the archive is unbounded, as Matthieu said if A is not added because is already included, then B1, ..., Bn should have been removed already when A was inserted the first time or, they would have never been inserted after A was already there. 

If the archive is bounded there is still the possibility that A would not be inserted because is the one selected by the prune method to be removed. This would only happens if the archive is already at the maximum size and A is also a candidate to be there (in other words is non-dominated regarding the archive content). In this case then A does not dominate any soluiton. 

Therefore it seems is not possible that it happens. In any case, as I may be forgetting any special case (like the archive is reduced in more than one element after trying to insert A, no matter whether B is non-dominated or dominated with A), it is not bad having that situation also included as return possibility.

**Comment by matthieu-vergne** [comment]
Let's be open minded: suppose that someone designs an archive where each time you add a solution, the boundary is decreased. Then you could imagine that adding A returns a collection with A, because it is dominated so it should not be added, and some other Bs, because the size has decreased and the archive is already full.

Such a case may happen for instance if someone want an algorithm based on an archive, thus a non-dominated population, to which he adds a specific pruning method, such that if the algorithm should run for N iterations, the archive starts with a boundary of N + 1 and decreases at each iteration to finish at 1 (or a more complex evolution, like from 2^N to 1 by dividing by two at each iteration). The unique solution remaining would be the final solution to return. This could be interesting for instance if you have an evaluation function for which you can parameter the precision, and more precision you want, more time it needs to compute. So basically, you start with a lot of solutions and a low precision, and more your population (archive) evolves with better solutions, more you want the precision to increase to better see the small diferences between similar solutions, thus increasing the computation time. Decreasing the archive boundary at each iteration would allow to free some resources for the evaluation function, so you may guarantee that computing a single iteration never exceeds some time limits (and prove that your algorithm finishes).

This is completely imaginary, and surely he could just have the addition at one step and the archive reduction at another instead of combining them. But it is not forbidden, so it may happen. Whether or not such a design is the best one is a different matter.

**Comment by ajnebro** [comment]
That idea is not imaginary. I remember a paper of Carlos A. Coello where he proposed an algorithm based on a similar concept: by using a binary-real encoding, the algorithm started with low precision (few bits per real number) with the idea of promoting diversity and during the search the precision was increased progressively to intensify the search. What I don't remember is whether that algorithm used an archive or not.

Anyway, I think that the `Archive` interface covers that kind of archive and, on the other hand, I'm affraid that if we consider in all the possible variants, we can have the problem of over-generalization.

Finally, you have exposed an idea that, is elaborated a bit, could lead to an interesting algorithm ;)

**Comment by matthieu-vergne** [comment]
The point is not to think about all the cases, but to build a rigorous definition, stick to it for the interface, and revise it only when we find an example that we expect to be managed but is not. Looking for weird (or not) cases should be a way to stress the generality of the definition. Over-generalization mainly come when we have no clear idea of what should be done, which lead to generalize as long as we find cases which are not covered (whether or not they should be covered). When finding a case which is not covered, we should first think about the relevance of covering this case, and only when we think that it *must* be covered, then we may generalize.
