### ISSUE TITLE
Time to rethink the `AbstractGeneticAlgorithm` abstract class

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#110]
An issue raised at #100 was the poor design of the [`AbstractGeneticAlgorithm` class](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/algorithm/impl/AbstractGeneticAlgorithm.java):

``` java
public abstract class AbstractGeneticAlgorithm<S extends Solution<?>, Result> extends AbstractEvolutionaryAlgorithm<S, Result> {
  protected SelectionOperator<List<S>, S> selectionOperator ;
  protected CrossoverOperator<S> crossoverOperator ;
  protected MutationOperator<S> mutationOperator ;
}
```

After working with jMetal 5 some new issues have appeared related to it:
- The selection operator requires a `List<S>` and returns a single solution `S`, but there are selection operators that returns also a `List<S>` (e.g. the `DifferentialSelectionOperator`), so they cannot be used.
- Many genetic algorithms share the same default implementations of some of the methods of the `AbstractEvolutionaryAlgorithm` template, but currently the same code is repeated in all them:

``` java
  @Override protected List<S> createInitialPopulation() {
    List<S> population = new ArrayList<>(populationSize);
    for (int i = 0; i < populationSize; i++) {
      S newIndividual = problem.createSolution();
      population.add(newIndividual);
    }
    return population;
  }

  @Override protected List<S> evaluatePopulation(List<S> population) {
    population = evaluator.evaluate(population, problem);

    return population;
  }

  @Override protected List<S> selection(List<S> population) {
    List<S> matingPopulation = new ArrayList<>(population.size());
    for (int i = 0; i < populationSize; i++) {
      S solution = selectionOperator.execute(population);
      matingPopulation.add(solution);
    }

    return matingPopulation;
  }

  @Override protected List<S> reproduction(List<S> population) {
    List<S> offspringPopulation = new ArrayList<>(populationSize);
    for (int i = 0; i < populationSize; i += 2) {
      List<S> parents = new ArrayList<>(2);
      parents.add(population.get(i));
      parents.add(population.get(i + 1));

      List<S> offspring = crossoverOperator.execute(parents);

      mutationOperator.execute(offspring.get(0));
      mutationOperator.execute(offspring.get(1));

      offspringPopulation.add(offspring.get(0));
      offspringPopulation.add(offspring.get(1));
    }
    return offspringPopulation;
  }
```

which also have led to discovering some errors (#107), not to mention the fact that the same unit tests should be repeated.

  The point is, should this common behavior be included in the `AbstractGeneticAlgorithm` class or  moved to the `AbstractEvolutionaryAlgorithm` class?

**Comment by matthieu-vergne** [comment]
Neither one nor the other. I think rather that it is time to properly exploit your operators. For `AbstractEvolutionaryAlgorithm`, replace abstract methods by non-abstract operator getters+setters (the whole class should become non-abstract), and move these common pieces of code to dedicated operators that you just reuse in specific algorithms. Then, you can have dedicated unit tests for these operators, while test for the algorithms will focus on ensuring that they interact as expected.

This is not only a way to exploit `Operator`, but also a way to:
- make `AbstractEvolutionaryAlgorithm` non-abstract, so you can properly test it too
- ensure future code simplification with the [lambda expressions](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html) of Java 8

**Comment by matthieu-vergne** [comment]
Then you can have default operators provided by the `AbstractEvolutionaryAlgorithm` if you want, but if it introduces additional dependencies (e.g. the problem) then I would not recommend it.

**Comment by matthieu-vergne** [comment]
Additionally, `AbstractGeneticAlgorithm` may be rewrite to set some operators and ask for other, new and more specific operators.

**Comment by ajnebro** [comment]
I'm comming back to this issue.

> Neither one nor the other. I think rather that it is time to properly exploit your operators. For AbstractEvolutionaryAlgorithm, replace abstract methods by non-abstract operator getters+setters (the whole class should become non-abstract), and move these common pieces of code to dedicated operators that you just reuse in specific algorithms. 

and I'm not sure to understand the approach. Is the idea to replace methods such as:
``` java
  protected abstract void initProgress();
  protected abstract void updateProgress();
  protected abstract boolean isStoppingConditionReached();
  protected abstract List<S> createInitialPopulation();
  ...
```

by operators?

**Comment by ajnebro** [comment]
Ok, after reading issue #100 again I get your point.

**Comment by matthieu-vergne** [comment]
Which is yes, just to make it clear. {^_°}

**Comment by ajnebro** [comment]
I'm exploring your idea.

I have replaced this code:
```java
  protected abstract List<S> createInitialPopulation();
  protected abstract List<S> evaluatePopulation(List<S> population);
  protected abstract List<S> selection(List<S> population);
  protected abstract List<S> reproduction(List<S> population);
  protected abstract List<S> replacement(List<S> population, List<S> offspringPopulation);
```

by this one:
```java
  protected Operator<List<S>, List<S>> createInitialPopulation;
  protected Operator<List<S>, List<S>> evaluatePopulation ;

  protected Operator<List<S>, List<S>> selection;
  protected Operator<List<S>, List<S>> reproduction;
  protected Operator<List<S>, List<S>> replacement;
```
and there are some questions. 

Question 1: It doesn't seem to make sense to replace these methods:
```java
  protected abstract void initProgress();
  protected abstract void updateProgress();
  protected abstract boolean isStoppingConditionReached();
``` 
by operators.

Question 2. The original replacement method has two arguments:
```java
  protected abstract List<S> replacement(List<S> population, List<S> offspringPopulation);
```
and I don't see a simple way to use the replacement as an operator given that the `execute()` method of operators has only one parameter.

**Comment by ajnebro** [comment]
> Then you can have default operators provided by the AbstractEvolutionaryAlgorithm if you want, but if it introduces additional dependencies (e.g. the problem) then I would not recommend it.

Practically all the default implementations of all the algorithms have this method, which is problem-dependant:
```java
  @Override protected List<S> createInitialPopulation() {
    List<S> population = new ArrayList<>(getMaxPopulationSize());
    for (int i = 0; i < getMaxPopulationSize(); i++) {
      S newIndividual = problem.createSolution();
      population.add(newIndividual);
    }
    return population;
  }
```

I'm resisting the temptation of adding it to the `AbstractEvolutionaryAlgorithm` class because of the problem dependence ... but that seems to be the logical place.

**Comment by matthieu-vergne** [comment]
First, a general comment: I recommend you to use private members and add the corresponding public setters and getters (or only getters if you want to set them only through the constructor). This way, you enforce external users to use of the methods instead of the members. If you don't, the day you want to change your internal implementation to use something more complex, you will have to deal with backward compatibility. For the local implementation it is true that it adds lines of code, but it remains simple and it does not change much for the user of the class or child classes (replace member names by method names), so I think it is a good habit to avoid future complications and maintain some homogeneous coding conventions. An example of complex implementation is if you want to use a combined operator (which requires simple operators and use them in a specific way). In such a case, you need a variable only for the combined operator, but because you want this combined operator to be fixed (not let the user change it because you need this one in particular), you should provide setters/getters for the simple operators it contains, so you hide the complexity of the algorithm and ask simple stuff to the user.

> Question 1: It doesn't seem to make sense to replace these methods:
```java
protected abstract void initProgress();
protected abstract void updateProgress();
protected abstract boolean isStoppingConditionReached();
```
by operators.

For `initProgress()` and `updateProgress()`, I guess it is hard to imagine an operator, because they have no input nor output while an operator is supposed to build an output based on an input. Technically speaking, nothing forbid to use an operator anyway: you can use `Void` (notice the uppercase) for filling the generics, so you can have something like that:
```java
protected Operator<Void, Void> initProgress;
protected Operator<Void, Void> updateProgress;
```
which means that, whatever they do, their input and output can only be `null`. You still need to call the `operator.execute(...)` method with an argument, but this argument must be `null`. Here is a code example:
```java
public class MyOperator implements Operator<Void, Void> {

	@Override
	public Void execute(Void source) {
		// ...
		// Actions of the operator
		// ...
		
		return null; // required
	}

	public static void main(String[] args) {
		MyOperator operator = new MyOperator();
		
		operator.execute(null); // execute the actions but returns null
	}
}
```

With that, you might understand that `isStoppingConditionReached()` can be replaced by:
```java
protected Operator<Void, Boolean> isStoppingConditionReached;
```

Moreover, you might reflect a bit more about how you refined the method `createInitialPopulation()`, which does not have any input (like `isStoppingConditionReached()`) yet you replaced it by an operator taking a `List<S>`:
```java
protected Operator<List<S>, List<S>> createInitialPopulation;
```

Now, this is the purely technical perspective. Regarding the relevance of such choices, I agree that it does not make much sense for the progress methods to be replaced by operators. Actually, using `Void` is an hint of potential misalignment, so if we have to use `Void` everywhere, there is probably a problem. For me, both these methods relate to a `Measure`, because they are intended to deal with the progress of the computation, which is not something that you actually care about normally. I assume that you added them in order to extract the responsibility of dealing with measuring the progress. Rather, you should have some kind of `Measure` here instead of these two methods. This `Measure` should be reset at the start of `run()` and updated at the end of each iteration. Then, by registering a `MeasureListener` on this measure, any external entity can get information about the progress in real time, which is the equivalent of implementing both the init and update methods that you have now. Additionally to "start using operators" I might have also said "start using measures", and these methods would have been the relevant candidates for the latter. {^_^}

This is for the progress methods. For the stopping condition and the initial population, they seem to me to be good candidates for operators, although they (a priori) need `Void`. As I see an operator, it aims at providing something (the output) which might be dependent on something else (the input). If your input is complex, you can use a couple or something richer in order to reduce all the parameters to a single one. But the reverse is also possible: it may be that you just need no information at all to produce the output. So from my point of view, the output is required, while the input is optional, which is why I think that it makes sense for them to use operators.

However, if you look at the implementation, you might see that actually it needs some information: the population creation needs the size of the population, which appears to me as a relevant input because you tell to the algorithm how big should be the population it manages, so this information is under the responsibility of the algorithm and not of the specific operator that you use. So make it an input in order to make the operator independent of the algorithm (when the algorithm uses the operator, it provides its information through the input). Another element, that you pinpoint in your last post, is the dependence to the problem, which is the one knowing how to create the solution. Same thing: you tell to the algorithm which problem to solve, the operator should be applicable to any problem. So I would basically create an operator `CreatePopulation` which takes as input a couple (problem, size) and returns a population. Seeing further, it would be actually a couple (solution builder, size), where the solution builder can be a problem or an algorithm, but this relates to more advanced decoupling like I did in #73.

I take this occasion to answer your last concern:
> Practically all the default implementations of all the algorithms have this method, which is problem-dependant:
```java
  @Override protected List<S> createInitialPopulation() {
    List<S> population = new ArrayList<>(getMaxPopulationSize());
    for (int i = 0; i < getMaxPopulationSize(); i++) {
      S newIndividual = problem.createSolution();
      population.add(newIndividual);
    }
    return population;
  }
```
I'm resisting the temptation of adding it to the AbstractEvolutionaryAlgorithm class because of the problem dependence ... but that seems to be the logical place.

First, although I agree that there is a problem dependence here, this is a generic one: `createSolution()` comes from the root class `Problem`, so there is no dependence to a specific type of problem, which is what I meant: don't introduce dependences to `AbstractDoubleProblem` for instance, because all `AbstractEvolutionaryAlgorithm` do not deal with this kind of problem, but all deal with problems in general, so you can transfer it in higher level classes.

> Question 2. The original replacement method has two arguments:
```java
  protected abstract List<S> replacement(List<S> population, List<S> offspringPopulation);
```
and I don't see a simple way to use the replacement as an operator given that the execute() method of operators has only one parameter.

Basically, the point here is to consider the single couple (population, offsprings) and make the dedicated structure. You already implemented stuff like that, this is the same here.

**Comment by matthieu-vergne** [comment]
I have started to work on this change locally, and the point is that your templates are completely oblivious to this problem, which means that whether your problem is, practically, useless at this level, whether your should revise your templates to consider it. Otherwise it just add to my own position, which is that an algorithm does not depend on a problem. Actually, so far the problem variables that you included in high level classes, like in `AbstractEvolutionaryAlgorithm`, are mere syntactical optimizations (you factor a code common to some child classes and impose it on all the hierarchy). I was actually ready to have the same thing that my pull request #159 but for problems.

So if you want to go ahead with integrating the problem into the algorithm, which would make sense if we take your model as a reference, it means that some other modifications should be considered too to integrate it properly.
