### ISSUE TITLE
Set and get attributes for operators

### ISSUE THREAD

**Issue by shaikatcse** [jMetal/jMetal#115]
Hi there,

Is it possible to set and get attributes for operator (similar to solutionAttribute)? Sometimes it is required to set attribute of some operator on run-time (e.g.: changing distribution index depending on generation). I need to set some attribute/value to selection operator on run-time. How could I do that?

Thanks. 
Regards,
Shahriar

**Comment by matthieu-vergne** [comment]
Initially nothing forbid it, but this is an implementation choice (using static or dynamic attributes), and so far the habit is still to provide everything in the constructor. So operator attributes are given to operator constructors, and operator instances are given to algorithm constructors. Some operators actually have setters, like `NonUniformMutation.setCurrentIteration(...)` or `DifferentialEvolutionSelection.setIndex(...)`, but it is not the general way to do. At least yet.

This is something which might change in the future, because even now there is classes which rely on abstract methods to implement instead of operators to set, which is not really flexible. But for now, the general recommendation I would give, if you need to update your operator, is to implement your own (extending the original one to add a setter could be enough, you have to check the source code) and to give it to your algorithm. You might also consider to change directly the original operator and make a pull request with your changes if you think it is generally better that way.

**Comment by ajnebro** [comment]
Hi Shahriar.
  As Matthieu suggests, there is no problem in changing the original code to provide new features if they are needed. 

  Acording to your question, I assume that you refer to operators such as `PolynomialMutation` and `SBXCrossover`. Both of them provides methods (getters) for obtaininig their probabability and distribution indexes, and there is not any reason to not include setters as well.

I have just modified those two classes with the setters in the current jMetal development version.

**Comment by matthieu-vergne** [comment]
Should we close the issue?
