### ISSUE TITLE
a bug in AdaptiveGridArchive

### ISSUE THREAD

**Issue by White-Chen** [jMetal/jMetal#121]
In the `AdapativeGridArchive.class`, from the annotation we can know that the author just want to use the prune method to delete one solution from rep.
```
    107      // Remove an solution from most populated area
    108      prune();
    109      // A solution from most populated hypercube has been removed,
    110      // insert now the solution
```
However, there is a bug in the method.
```
  public void prune() {
	  Iterator<S> iterator = getSolutionList().iterator();
      boolean removed = false;
      while (iterator.hasNext()) {
        if (!removed) {
          S element = iterator.next();
          int location2 = grid.location(element);
          if (location2 == grid.getMostPopulatedHypercube()) {
            iterator.remove();
            grid.removeSolution(location2);
          }
        }
      }
  }
```
I think the para. removed is a flag to tell the loop when to stop, but actually it never be reassigned in loop. So if we use the method, it will clean the mostPopulatedHypercube not remove one. 
The right implement is following？
```
  public void prune() {
	  Iterator<S> iterator = getSolutionList().iterator();
      boolean removed = false;
      while (iterator.hasNext()) {
        if (!removed) {
          S element = iterator.next();
          int location2 = grid.location(element);
          if (location2 == grid.getMostPopulatedHypercube()) {
            iterator.remove();
            grid.removeSolution(location2);
            //make sure that only one solution will be removed
            removed = true;
          }
        }
      }
  }
```

**Comment by matthieu-vergne** [comment]
I have several things to add for clarity purpose (not bug fixing), but I have to say that I did not look the actual code. I only look at the piece of code given here. So some of my comments might be irrelevant. I know it's bad, but sometime laziness is stronger than wisdom. {^.^}~

First, I agree that, with `removed` being set only at `false` in the beginning, it has no use unless there is a bug. But I go a bit further in the reasoning before to jump on conclusions.

Second, the name of the method is not clear at all: prune means "remove some stuff", but it does not tell what to remove nor to which extent. It might be for removing a single solution, or to remove anything in the least populated hypercube, or to remove everything which is not in the most populated hypercube (if I consider the last `if` condition). If I have a `prune` method, I would expect to have an argument to tell what should be pruned, but it is not the case. So I assume that it should prune in a specific way, and this way should be reflected in the name, like `pruneWorstSolution` or `pruneLeastPopulatedHypercube`. If the aim is to remove only 1 solution which is not in the most populated hypercube, I would say `pruneNotBestSolution` or something alike, the point is that we just remove a random solution as long as it is not in the most populated hypercube, which seems to me quite arbitrary and need some clarifications (at least in the documentation of the method). Only when the goal of the method is strictly defined we can name it properly to represent that, rather than give it an uninformative name that we need to clarify with comments when we use it, like it is now.

Third, there is an anti-pattern here (well, I claim it is one): you have a loop on a list, loop which has its full content enclosed in a single `if`. It makes sense when you want to apply some treatments to some specific items of the list, without knowing where they are in the list. However, here the condition is not about which items are the ones to treat, but about a flag supposed to be switched when the code has been fully executed, which is the aim of a stopping condition. Long things short: you have split the stopping condition of your loop to share it with an internal `if`, which not only decreases the clarity of your code but also increases the chances to make wrong stuff. For instance, I have seen not long ago a bug causing an infinite loop with that kind of split in the core of the problem (the stopping condition was cut into 3 levels, here you have 2). Assuming that the fix above is the right one, I would merge the stopping conditions:
```java
Iterator<S> iterator = getSolutionList().iterator();
boolean removed = false;
while (iterator.hasNext() && !removed) {
    S element = iterator.next();
    int location2 = grid.location(element);
    if (location2 == grid.getMostPopulatedHypercube()) {
        iterator.remove();
        grid.removeSolution(location2);
        removed = true;
    }
}
```
This also allows to avoid continuing browsing the list when we have already removed the solution, so it removes useless computation.

Additionally, you may consider that, because this method aims at doing a single removal, it is finished as soon as the removal is done, so you might replace the `removed` flag by an explicit `return`:
```java
Iterator<S> iterator = getSolutionList().iterator();
while (iterator.hasNext()) {
    S element = iterator.next();
    int location2 = grid.location(element);
    if (location2 == grid.getMostPopulatedHypercube()) {
        iterator.remove();
        grid.removeSolution(location2);
        return;
    }
}
```
Then, one may suggest you to use a `for` loop in this case (`for(S element : getSolutionList())`) to remove all the iterator stuff, but because you need to remove the solution the iterator might be more efficient. So I would not recommend it.

Finally, `prune` is not the only thing having an unclear name:
- `location2` is an `int`, not a solution, so `grid.removeSolution(location2)` makes no sense.
- `location2` being compared to `grid.getMostPopulatedHypercube()`, the vocabulary does not match: a hypercube is not a location, as far as I know. You probably don't get the hypercube itself but some kind of index.
- `location2` can be renamed as `location`, and using `X1, X2, ...` is an hint that you should maybe take some more time to think about the aim of your variables to keep the code clear.

**Comment by White-Chen** [comment]
Yes, I agree that some names of methods and variables are not clear in the source code, sometimes it make me comfused.
