### ISSUE TITLE
Measures and WeakHashMap

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#130]
To configure and run experiments in jMetal 5 (yes, I must open an issue about that ASAP), in the current approach all the algorithms need to be serialized. As a consequence, most of the classes and interfaces must implement the `Serializable` interface.

The issue is that seems that the `WeakHashMap` class, used in the measures, is not serializable. The question is, can we replace it with `HashMap`?

**Comment by matthieu-vergne** [comment]
# Obvious wrong answer (you would not ask otherwise)

Yes you can, it is just a map after all.

# Better but half wrong answer (apparent good answer, but actually dangerous)

Of course not. `WeakHashMap` is a really special map which affects the garbage collecting process. Surely enough if we use this it is to exploit this specificity, but you can also generalize that answer to any implementation. Rather than wondering whether you can replace an implementation by a different one, you will be safer by creating your own class which extends the faulty class and implement the additional stuff you want. So prefer to make a class `SerializableWeakHashMap extends WeakHashMap implements Serializable` and use it instead of the original one.

# Best answer (as far as I know)

The whole point of the `WeakHashMap` is to allow some stuff to be garbage collected if it is not used elsewhere. `Serializable` allows to transfer a piece of code from a JVM to another. If you transfer a `WeakHashMap` alone to a different JVM, then surely enough its content will be garbage collected, because it is then the only one using its own content. Consequently, it is hard to motivate that such an object should be serialized.

If you want to do so I think that you need something more complex than just making it `Serializable`, because you also need to ensure that the stuff stored in the `WeakHashMap` and used elsewhere is serialized in such a way that, once transferred, you retrieve that stuff in the new `WeakHashMap` and in the new "elsewhere" too, otherwise it will be garbage collected. Maybe making it `Serializable` will work, maybe not, it depends what you serialize, how you do it, and how the serialization is managed under the cover. But I would not be surprised that it does not work as expected.

Please check out [the documentation of `Serializable`](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html). There is several important things to read, but in particular this one:
> To allow subtypes of non-serializable classes to be serialized, the subtype may assume responsibility for saving and restoring the state of the supertype's public, protected, and (if accessible) package fields.

In short, if you make your own `SerializableWeakHashMap`, you need to pay particular attention whether `WeakHashMap` already has some fields that you need to store and retrieve too, because it won't be done automatically, which is for sure the case because the entries are managed by the parent class, not your own. This documentation also tells you about how to handle them through additional methods, but what I think would be more interesting is to use them on the classes using this `WeakHashMap` rather than the maps themselves. For instance, in the case of [`ListenerTimeMeasure`](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/measure/impl/ListenerTimeMeasure.java), I would keep the two `WeakHashMap` fields but make them [`transient`](http://stackoverflow.com/questions/910374/why-does-java-have-transient-variables) (so they are ignored by the serialization process), then add the `writeObject(out)` to write the content of these maps (practically, you write first the size of the first map, then for each entry you write the key followed by the value, then same thing for the other map) and add the `readObject(in)` to retrieve this content (practically, read the size of the first map, then read as many keys followed by values to feed the map, then same thing for the second map). You can find more explanations on this process [here](https://docs.oracle.com/javase/7/docs/platform/serialization/spec/serial-arch.html). You may also be interested in the `serialPersistentFields` alternative, also described in the latter.

These methods should only ensure that (i) the reading retrieves all the (not managed) required information to rebuild the object correctly, and (ii) the writing provides this information in the same order it needs to be retrieved. By using them, you can also gain in performance too, because you can reduce the amount of information sent (e.g. send only the size of the map instead of the full map object). Pushing this idea to the extreme, you can force yourself implementing these methods by using `Externalizable` instead of `Serializable`, in which case nothing is done automatically, but you also don't need to specify what is `transient`, so all the serialization is explicitly stated in these read/write methods.

Maybe all what I said before was not that clear, in which case I recommend you to read [this article](http://www.oracle.com/technetwork/articles/java/javaserial-1536170.html) which provides a great introduction, broad but short and illustrated. Then my prose should be clearer.

In short, `Serializable` is nice, but it is good for simple uses. If you start using it generously, then probably you should pay a bit more attention to what is done and prefer to exploit the additional write/read methods when you deal with complex objects. Otherwise you may run in nasty bugs really hard to fix.

**Comment by ajnebro** [comment]
I'm not precisely a fan of serialization. Many years ago I had to deal with serializing objects when communicating distributed processes by using raw sockets ... it was really a pain in the ... 

The point is that if we intend to execute jMetal algorithms in a cluster all their components should be serialized if we don't to waste time with that issue.

**Comment by matthieu-vergne** [comment]
The point is precisely that if you need it, then you have to use it
correctly, and for that you need to know how it works. I don't think that
blindly making everything extend `Serializable` will be helpful, but rather
the opposite. You have to understand how it works in order to use it
properly, like any other tool. I agree it is not straightforward at first,
like `Thread`, but once you have practiced a bit at the deepest level (i.e.
by writing these writing/reading functions), at the end you understand that
what makes it complex is actually not the serialization process at all (it
is just a read/write process), but the complexity of your own objects
(which makes the choice of what to serialize and how to do it difficult).

I am not that familiar with your cluster stuff. So explaining your context
would be helpful. But I am pretty sure that you can avoid making everything
`Serializable` by choosing just the right stuff and using these read/write
methods properly. Yet, to choose it well, you have to know how it works. If
you don't, then you can ask, but I don't know well your context, so I can
only say generic stuff. Whether you explain me your context, whether you
form yourself on serialization, but at the end someone should well
understand both to provide the right advices.
