### ISSUE TITLE
Alternative solution implementations for a given problem

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#144]
This an issue I have in mind since we started with jMetal 5. I'm going to open it although I haven't found yet any case where it can cause any trouble.

This issue is the following. Let us consider the [`AbstractDoubleProblem`](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/problem/impl/AbstractDoubleProblem.java) class: 

``` java
public abstract class AbstractDoubleProblem extends AbstractGenericProblem<DoubleSolution>
  implements DoubleProblem {

  private List<Double> lowerLimit ;
  private List<Double> upperLimit ;

  /* Getters */
    @Override
    public Double getUpperBound(int index) {
        return upperLimit.get(index);
    }

    @Override
    public Double getLowerBound(int index) {
        return lowerLimit.get(index);
    }

  /* Setters */
  protected void setLowerLimit(List<Double> lowerLimit) {
    this.lowerLimit = lowerLimit;
  }

  protected void setUpperLimit(List<Double> upperLimit) {
    this.upperLimit = upperLimit;
  }

  @Override
  public DoubleSolution createSolution() {
    return new DefaultDoubleSolution(this)  ;
  }
}
```

This class is implemented by all the continuous problems defined in jMetal. The idea is that this approach should be flexible enough to allow different implementations of `DoubleSolution` for any given continuous problem, but currently the `createSolution()` method returns an instance of a particular implementation (`DefaultDoubleSolution`). 

Let take as an example the [Schaffer problem](https://github.com/jMetal/jMetal/blob/master/jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/Schaffer.java). A simple solution could be to define a subclass of it which would override the `createSolution()` method to return an instance of a different implementation of `DoubleSolution`. 

This approach should work, but I'm not sure whether a more elegant solution could be adopted.

**Comment by matthieu-vergne** [comment]
# Technical Perspective

Well, thinking quickly about it I see two potential alternatives to bring some flexibility in the architecture, whether or not they are "conceptually sound".

## Solution generator

One answer is to design your class in order to use a solution generator in `createSolution()`. Something like this:
```java
interface SolutionGenerator<S extends Solution, P extends Problem> {
  public S generates(P problem);
}
```
Which then would be used like this:
```java
public void setSolutionGenerator(SolutionGenerator<DoubleSolution, DoubleProblem> generator) {...}

public SolutionGenerator<DoubleSolution, DoubleProblem> getSolutionGenerator() {...}

@Override
public DoubleSolution createSolution() {
  return generator.generates(this);
}
```
I did not try it, and I am pretty sure there would have problems if you copy paste, because the problem generics is tricky (should it be a generic one -interface-? should it be the current class? should it be actually not constrained, etc.). One issue is that your solution depends on the problem, which makes them entangled which means you have spaghetti code (problem depends on solution which depends on problem). I don't develop this point, you already know it and we are working on that in issue #71. But I think fixing this spaghetti point would make it easier to think about the current issue.

## Configure rather than create

You may replace your `createSolution()` as a `configureSolution(solution)`, so another one should instantiate it and the problem only assigns the relevant property to make it a solution related to the problem. But now, such an alternative would just move the problem elsewhere: you still need to decide who will generate the solution to pass in argument and you would have probably many issues with the hierarchy of interfaces and classes of solutions.

Although I think it is not a good idea with the current architecture, it might be worth mentionning it because it links to the next section.

# Ontological perspective

Now, if I think about the ontological/philosophical perspective, then the point is that you dedicated to your problem the responsibility of generating a solution, thus it makes sense that your problem decides which implementation to use. If you think that it must be flexible to various classes, then it seems you are contradicting yourself. I claim that this is what shows that your current idea of solution includes several concepts which should be decoupled. In which case it might be the right time to think about which specific aspects of the solution you think should be problem-related, and which other aspects of the solution should not.

And for that, I drive you back to [this comment](https://github.com/jMetal/jMetal/issues/71#issuecomment-104486872) about attributes (generic solution, problem-specific attributes). Just think about it by yourself to try to find out which aspects of a solution should be decided depending on the problem itself and which aspects should not. Then read this comment and try to see if it corresponds to your idea.
