### ISSUE TITLE
Normalizing front when difference between maximum and minimum is zero

### ISSUE THREAD

**Issue by rhrlima** [jMetal/jMetal#147]
Hi,

I'm facing a situation where I get an Exception for having the max and min values for a certain index equal to zero when normalizing a front for Hypervolume calculation.

`normalizedFront.getPoint(i).setDimensionValue(j, (front.getPoint(i).getDimensionValue(j)
                        - minimumValues[j]) / (maximumValues[j] - minimumValues[j]));`

There is a default solution for this kind of situation? What I'm doing is setting the normalized value as the current value minus the min value ignoring the division.

Thanks.

**Comment by matthieu-vergne** [comment]
If max = min, then all the values are normally the same, so once they are normalized they should be also all the same. You could just use the value 1 or any other value in [0;1] for everyone, so you maintain the idea of using a normalized value. With your fix (and if the code around is correct), you use 0 for everyone, so rather than removing the division, directly take 0 to save even more computation.
