### ISSUE TITLE
Algorithm PESA2 can't run without setting the maximum population size

### ISSUE THREAD

**Issue by SunnyWind** [jMetal/jMetal#152]
There should be a statement `this.setMaxPopulationSize(populationSize);` setting the max population size after line 52 in class `org.uma.jmetal.algorithm.multiobjective.pesa2.PESA2`.
 Otherwise the PESA2Runner goes wrong because the method `createInitialPopulation()` in class `AbstractGeneticAlgorithm` uses the uninitialized variable `maxPopulationSize`, and it create ZERO population initially.
Right?

**Comment by matthieu-vergne** [comment]
# Population size

Indeed it seems that there is some clarifications which need to be made in the code. [`PESA2`](https://github.com/jMetal/jMetal/blob/master/jmetal-algorithm/src/main/java/org/uma/jmetal/algorithm/multiobjective/pesa2/PESA2.java) extends [`AbstractGeneticAlgorithm`](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/algorithm/impl/AbstractGeneticAlgorithm.java) (AGA) which extends [`AbstractEvolutionaryAlgorithm`](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/algorithm/impl/AbstractEvolutionaryAlgorithm.java) (AEA). The point is that AEA defines its `maxPopulationSize` which is then used by AGA to create the population in `createInitialPopulation()`. So at the lowest level, obviously the `populationSize` of `PESA2` is ignored.

Considering that nothing particular seems to be made with this redundant variable, my recommendation is to remove it from `PESA2`, and to use `setMaxPopulationSize(populationSize)` in the constructor and `getMaxPopulationSize()` everywhere else.

# Selection operator

Meanwhile, `PESA2` also defines a `selectionOperator` which is already defined by AGA, so I recommend to fix also this redundancy at the same time. This one leads to a more complex issue, which is the overriden selection process. If overriding can be justified to decorate futher the method, replacing it totally how it is done now seems more an evidence of unsuited abstraction. Concretely, the main difference seems to use the archive instead of the current population to select mating individuals. My recommendation is to abstract the source of individuals to select with its own concept. So the current AGA selection process should be transformed from this:
```java
  @Override
  protected List<S> selection(List<S> population) {
    List<S> matingPopulation = new ArrayList<>(population.size());
    for (int i = 0; i < getMaxPopulationSize(); i++) {
      S solution = selectionOperator.execute(population);
      matingPopulation.add(solution);
    }

    return matingPopulation;
}
```
to something like that (not tested):
```java
abstract public List<S> getSelectionSource();

@Override
protected List<S> selection(List<S> population) {
    List<S> matingPopulation = new ArrayList<>(population.size());
    for (int i = 0; i < getMaxPopulationSize(); i++) {
      S solution = selectionOperator.execute(getSelectionSource());
      matingPopulation.add(solution);
    }

    return matingPopulation;
}
```
So the selection in PESA2 can be transformed from this:
```java
  @Override protected List<S> selection(List<S> population) {
    List<S> matingPopulation = new ArrayList<>(populationSize) ;

    for (S solution : population) {
      archive.add(solution) ;
    }

    while (matingPopulation.size() < populationSize) {
      S solution = selectionOperator.execute(archive) ;

      matingPopulation.add(solution);
    }

    return matingPopulation ;
}
```
to something like that (not tested):
```java
@Override public List<S> getSelectionSource() {
    return archive;
}

@Override protected List<S> selection(List<S> population) {
    for (S solution : population) {
      archive.add(solution) ;
    }

    return super.selection(population);
}
```
which maximises the reused code. Other classes which extend AGA would simply return their population as the selection source.
