### ISSUE TITLE
MOPSO

### ISSUE THREAD

**Issue by Lassaad-Zaaraoui** [jMetal/jMetal#153]
Hi,
I download jmetal 4.5.2.src.tar , but I did’nt find only the files OMOPSO, SMPSO , and DMOPSO and I did’nt find the MOPSO.java file !!!
Is it named the file mopso.java here, dmopso.java?
Thanks;

**Comment by matthieu-vergne** [comment]
Considering that it is the 4.5 version (the old one) I will let Antonio reply. I am more familiar with the current version (jMetal 5) which has a lot of changes.

**Comment by Lassaad-Zaaraoui** [comment]
ok thank you, but in the jMetal 5 I did'nt fint the file MOPSO.java !!!
any idea about this situation ?

**Comment by matthieu-vergne** [comment]
Please wait for @ajnebro or @Juanjdurillo to reply to you. No need to push for it nor to make duplicate issues (you can close the #154 that you created).

Meanwhile, please describe your context and tell us why you need these files.

**Comment by Lassaad-Zaaraoui** [comment]
I am very sorry. 
I need these files because I work about the algorithms of PSO
MOPSO, OMOPSO and SMPSO. 
Sorry again.

**Comment by matthieu-vergne** [comment]
It seems that even on the 4.5 branch available [here](https://github.com/jMetal/jMetal/tree/jmetal45) there is no file named `MOPSO.java`. The [search feature](https://github.com/jMetal/jMetal/search?utf8=%E2%9C%93&q=mopso.java) is unable to find one.

So if you really need these files and not others, the only thing you can do is wait for @ajnebro or @Juanjdurillo.

Otherwise, you may try the new version of jMetal, the 5.1 available [here](https://github.com/jMetal/jMetal/tree/jmetal-5.1).

**Comment by Lassaad-Zaaraoui** [comment]
Ok.  Thank you very much

**Comment by Juanjdurillo** [comment]
Hi Lassaad, 

as I told you by mail a couple of days ago, currently we do not have any implementation of the original MOPSO algorithms in any of the two releases of jMetal. 

Personally, I would consider OMOPSO instead of MOPSO. OMOPSO (Optimized MOPSO) is also an algorithm designed by the same authors as the original MOPSO. It has been shown to outperform the original one in most of the benchmark problems.

**Comment by Lassaad-Zaaraoui** [comment]
Ok thank you for your help. 
Regards
