### ISSUE TITLE
“Variable” blocks the running 

### ISSUE THREAD

**Issue by haoguosheng** [jMetal/jMetal#165]
I came across an exception of  "Out of memory: GC overhead limit exceeded", shown as the following fig:
![image](https://cloud.githubusercontent.com/assets/5609432/18624547/259ee9f2-7e7b-11e6-92ec-c7e0b14859f4.png)
So it is necessary for us  to make a solution thinner to avoid such exception.

**Comment by matthieu-vergne** [comment]
Am I correct if I say that you use an old version of jMetal? Looking at the current code, there is no `jmeta.encodings` package. Could you please describe your context and what you are doing exactly?

**Comment by haoguosheng** [comment]
Oh, @matthieu-vergne, thank you very much.
I will try the new version of jMetal.
You know for each solution instance, there is "numberOfVariables" instances of Variable. When I try the problem Sphere("Real", 3000), where numberOfVariables==3000 for each solution. When population size is 50, there are 3000*50=150000 instances of Real. I run my program with multi-thread, the above exception appears.
Thank you very much!

**Comment by matthieu-vergne** [comment]
If I remember well, a huge number of variables has been a problem with jMetal, and it lead to use arrays instead of separate solutions (e.g. [`ArrayRealSolutionType`](https://github.com/jMetal/jMetal/blob/9545b0fc8fd5f8345f6206dd65a0161f497ab360/jmetal-core/src/main/java/org/uma/jmetal/encoding/solutiontype/ArrayRealSolutionType.java) instead of [`RealSolutionType`](https://github.com/jMetal/jMetal/blob/9545b0fc8fd5f8345f6206dd65a0161f497ab360/jmetal-core/src/main/java/org/uma/jmetal/encoding/solutiontype/RealSolutionType.java)). You may check with your old version whether you have these array variants and use them. I don't find them in the current code (jMetal 5.1), so you may face the same problem. Please try first the array variant with the old version, because there is still things which have not been ported to jMetal 5 yet. If you cannot achieve what you want with the old one, please go for the new one.

**Comment by haoguosheng** [comment]
@matthieu-vergne Thank you. I  downloaded the new version and compiled them.  Let me rewrite my codes based on your team's great work and run them again. 
Thank you again.

**Comment by ajnebro** [comment]
I thought that I had made a post here, but it seems that it is not here ...

The default implementation of the `DoubleSolution` interface uses a list to store the decision variables, so it can be inefficient if you need thousands of variables. The point is that there is no problem in defining a different implementation that can be more efficient (for example, by using an array instead of a list).

**Comment by haoguosheng** [comment]
@ajnebro Thank you. I thought the role that _Variable_ plays in _Solution_ and have a impulsion to modify the structure as following: For an optimized _Problem_, let all instances of _Solution_ share only one instance of _Variable_,  the difference is just a separated part which is the instance of a new defined class, whose fields is just the value of variable. By this, the space complexity will decrease dramatically. This is just a small idea and I hope to hear comments from you and @matthieu-vergne. 
Thank you again.

**Comment by matthieu-vergne** [comment]
I am not sure to understand, but it may be related to the notion of attributes we discussed in #71. You may also check out the code available for [solution attributes](https://github.com/jMetal/jMetal/tree/master/jmetal-core/src/main/java/org/uma/jmetal/util/solutionattribute) as it is implemented now.

**Comment by haoguosheng** [comment]
@matthieu-vergne I think I got it in [.](https://github.com/jMetal/jMetal/issues/71), which is really a very detailed issue. Thank you.
