### ISSUE TITLE
Time to move to Java 8

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#166]
Until now we have avoided to use Java 8 features in jMetal. The reason, in my case, was that we run jMetal code in Hadoop systems, which only supported Java 7, but now our Hadoop cluster has Java 8. 

So, unless someone give some reason against that, my idea is to start to use lambdas, streams, etc progressively.

**Comment by matthieu-vergne** [comment]
The last Ubuntu (16.04) also provides Java 8 in its repositories (through OpenJDK). So I don't see any reason to avoid it anymore.

**Comment by ajnebro** [comment]
Great :)

**Comment by ajnebro** [comment]
I'm thinking on how to proceed to adapt code to Java 8 (in re-reading again "Java 8 in Action").

Instead of merely changing particular pieces of code when we see the oportunity of doing so, perhaps it would be a better idea to start reviewing the core classes, indicating in this issue the change we intend to do, discussing it, and after aproving it, commit the modification.

**Comment by matthieu-vergne** [comment]
I would suggest you to go a step further: use this issue to discuss and list the different features of Java 8 that could be exploited in jMetal, and open a dedicated issue for each of them. In these dedicated issues, we can:
- discuss how to exploit the feature in jMetal
- agree on how to reliably identify the pieces of code to update
- agree on how to reliably update them
- provide commits for the issue

Once such a specific issue is closed, you can check the corresponding point in the list here. The list can be updated progressively if we find out other intereting features to exploit. Once the full list is checked, the new version can be released.

**Comment by ajnebro** [comment]
First version of the list of features:
* Default methods in interfaces
* Lamba expressions
* Streams
* Optional instead of null

**Comment by matthieu-vergne** [comment]
Based on the [list of features provided by Oracle](http://www.oracle.com/technetwork/java/javase/8-whats-new-2157071.html), what I think might be of interest to investigate:
- [Lambda expressions](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html), especially because we can use plenty of single-method interfaces in jMetal by just having their definitions (lambdas allow to "implement them" without actually doing so). Listeners are of particular interest.
- [Method references](https://docs.oracle.com/javase/tutorial/java/javaOO/methodreferences.html), which further simplify lambdas if the method already exists. For instance, methods can be provided by an algorithm (or an utilitary class) so we can reuse them easily to set up other algorithms which would need to get functions from the user (e.g. comparators, operators). In particular, it makes it particularly easy to replace mere values in arguments by functions, allowing to generate the values on demand, which can be useful when the value needs information that we can only acquire later in the run.
- [Default methods](https://docs.oracle.com/javase/tutorial/java/IandI/defaultmethods.html), which allow to implement high level algorithms as interfaces (with default implementations) instead of abstract classes. This would unlock the ability to implement several kinds of algorithms at once in order to combine easily there properties. Such a combination would be probably easier than thinking about extracting useful methods from existing algorithms in specifically redesigned classes just to be able to reuse them elsewhere.
- [Streams](http://www.oracle.com/technetwork/articles/java/ma14-java-se-8-streams-2177646.html), which can help to simplify many code pieces (with the help of lambdas) and to optimize. In particular, certain loops can be advantageously replaced by streams to ensure that we do not compute a full collection when there is no need to. However, it is common practice to reuse previously encountered information in loops (not just use it for the next step and forget), and I wonder if something can be done with streams at this level. To be investigated.
- Although not mentioned in the list, new interfaces/classes introduced for the sake of these improvements might be of interest too, like [Optional](http://www.deadcoderising.com/2015-10-06-java-8-removing-null-checks-with-optional/), but they have been designed [for specific purposes](http://blog.codefx.org/java/dev/design-optional/), and so should be carefully used.
- [Method parameter reflection](https://docs.oracle.com/javase/8/docs/technotes/guides/reflection/enhancements.html#a8), for retrieving proper variable names when importing external algorithms and wrap them into a jMetal `Algorithm`. This is a minor improvement, though.
- [Date-Time packages](http://docs.oracle.com/javase/8/docs/technotes/guides/datetime/index.html), although they are probably minor improvements, they may provide some better API for managing time. Especially if you want to let an algorithm run during a specific amount of time, whether it is as a user or as a tester.
- [Parallel array sorting and unsigned arithmetic support](http://docs.oracle.com/javase/8/docs/technotes/guides/lang/enhancements.html#jdk8), although it has to be tried and benchmarked to see if it is interesting.
- [Concurrency improvements](http://docs.oracle.com/javase/8/docs/technotes/guides/concurrency/changes8.html) for parallel computing. To be investigated.

Features that seems to me useless for jMetal:
- [Repeated annotations](http://docs.oracle.com/javase/tutorial/java/annotations/repeating.html) and [type annotations](https://docs.oracle.com/javase/tutorial/java/annotations/type_annotations.html), because it does not seem to me that you extensively use annotations. It might be interesting to investigate though, maybe we can exploit custom annotations for specific features.
- [Compact Profiles](http://docs.oracle.com/javase/8/docs/technotes/guides/compactprofiles/), because it is more for standalone apps, while jMetal is only a library.
- Security improvements, because jMetal is not about that, although the [high entropy random generator](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) may have some interests. Honnestly, I don't know. To be considered by people caring about the random generators used by default in jMetal.
- JavaFX improvements, because jMetal is not about GUI, although JavaFX might be interesting to provide some default GUI ready to use.
- Improved type inference, performance improvement for HashMaps with Key Collisions, tools improvements, scripting improvements, IO and NIO improvements, because they work behind the scene
- Internationalization, deployment improvements, pack200, base64 encoding/decoding, JDBC, Java DB, networking, Java XML/JAXP, HotSpot, because they are off topic.

**Comment by matthieu-vergne** [comment]
A bit more regarding newly introduced interfaces, through the package `java.util.function`:
- `Supplier<T>` for inputs, like parameters from the point of view of the algorithm
- `Consumer<T>` for outputs, like measures from the point of view of the algorithm
- `UnaryOperator<T>` for transformations, like mutation operators
- `Predicate<T>` for conditions, especially stopping conditions. A particularity is that it has a single parameter, which can be the algorithm instance. Such a use allows to design a stopping condition based on the properties of the algorithm, while the algorithm is not yet instantiated (i.e. a generic, reusable condition).

Regarding `Optional<T>`, it might be used for the result of the algorithm. If the algorithm fails to find a solution, then no solution is returned. However, it is hard to me to see what would be the practical advantage compared to returning `null`. May be it would be more interesting for operators and suppliers.

Another class of interest might be `SplittableRandom` for random numbers synchronized in parallel processing.

**Comment by matthieu-vergne** [comment]
@ajnebro Did you go ahead with some improvements towards using Java 8? I see there is some attempts in the develop branch, but nothing since December and nothing at all on the master branch. Do you have anything done locally, or is it really in pause?

**Comment by ajnebro** [comment]
I have used `stream()` and parallelStream()` in the [SequentialSolutionListEvaluator](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/evaluator/impl/SequentialSolutionListEvaluator.java) and [MultithreadedSolutionListEvaluator](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/evaluator/impl/MultithreadedSolutionListEvaluator.java) classes. 

What before was a bit complicated parallel code now is:

```java
 solutionList.parallelStream().forEach(s -> problem.evaluate(s));
```

As a consequence, the former `jmetal.util.parallel` package became useless and it was removed from the project.

**Comment by matthieu-vergne** [comment]
Sorry, I mixed my origin and upstream branches, so I did not see the new commits.
