### ISSUE TITLE
Refactor the add() method in class NonDominatedSolutionListArchive

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#173]
I would suggest to make a first try with Java 8 applying lambdas to the add() method of class [NonDominatedSolutionListArchive](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/archive/impl/NonDominatedSolutionListArchive.java).

**Comment by matthieu-vergne** [comment]
Do you have some tests for this method? To check whether we miss something when we adapt it.

**Comment by matthieu-vergne** [comment]
I am currently looking the method, and I am not sure it is the best one to apply streams.

Streams are like views in databases: the original data is still the same, but you create a new instance with the properties you are interested in. Here you would create a new list based on the original one, while the original one would stay unchanged.

`add(solution)` is supposed to change the list, by adding a new solution and removing obsolete ones. So by using streams we have to generate a new list (ad the end of the stream, use a `Collector` to obtain the result in a new list) and then replace the original one with the new one. This can be interesting if only few elements are kept, so instead of doing a lot of removal, you only do a bit of additions in a new list and swap the lists. But it does not seem to me that it is the case, rather the opposite (1 addition and few removals now, but many additions with streams).

So although it might simplify the code, I am not sure that it is the best place to use streams. From a performance as well as a conceptual perspective.

**Comment by matthieu-vergne** [comment]
Moreover, if the solution to be added is dominated, you currently stop the process before the end (which makes sense), while with streams you have to go through the end.

**Comment by matthieu-vergne** [comment]
Here are some refinements we can consider. None of them have been tested. I only wrote them to ensure that it compiles, but did not run them to see if they actually work.

# Analysis of the Existent

## Initial method

```java
public boolean add(S solution) {
	boolean solutionInserted = false ;
	if (solutionList.size() == 0) {
		solutionList.add(solution) ;
		solutionInserted = true ;
	} else {
		Iterator<S> iterator = solutionList.iterator();
		boolean isDominated = false;
		
		boolean isContained = false;
		while (((!isDominated) && (!isContained)) && (iterator.hasNext())) {
			S listIndividual = iterator.next();
			int flag = dominanceComparator.compare(solution, listIndividual);
			if (flag == -1) {
				iterator.remove();
			}	else if (flag == 1) {
				isDominated = true; // dominated by one in the list
			} else if (flag == 0) {
				int equalflag = equalSolutions.compare(solution, listIndividual);
				if (equalflag==0) // solutions are equals
					isContained = true;
			}
				
		}
		
		if (!isDominated && !isContained) {
			solutionList.add(solution);
			solutionInserted = true;
		}
		
		return solutionInserted;
	}

	return solutionInserted ;
}
```

For the sake of simplicity, I focus on the non-trivial case when the list is not empty:
```java
Iterator<S> iterator = solutionList.iterator();
boolean isDominated = false;

boolean isContained = false;
while (((!isDominated) && (!isContained)) && (iterator.hasNext())) {
	S listIndividual = iterator.next();
	int flag = dominanceComparator.compare(solution, listIndividual);
	if (flag == -1) {
		iterator.remove();
	}	else if (flag == 1) {
		isDominated = true; // dominated by one in the list
	} else if (flag == 0) {
		int equalflag = equalSolutions.compare(solution, listIndividual);
		if (equalflag==0) // solutions are equals
			isContained = true;
	}
		
}

if (!isDominated && !isContained) {
	solutionList.add(solution);
	solutionInserted = true;
}

return solutionInserted;
```

It is worth noting that we can already remove the trivial case without having much impact on performance because the while loop stops immediately if the list is empty. So we only compute:
```java
Iterator<S> iterator = solutionList.iterator();
boolean isDominated = false;
boolean isContained = false;
if (!isDominated && !isContained) {
	solutionList.add(solution);
	solutionInserted = true;
}
```
which is fundamentally the same than:
```java
solutionList.add(solution) ;
solutionInserted = true ;
```
with boolean assignments and evaluations being rather fast, the performance loss is rather small.

## Analysis

Basically, we have a loop where at each round (for each stored solution) we have these steps:
1. compute the dominance flag with the new comer
2. filter out if dominated by the new comer
3. compute the equality with the new comer

Additionally, we must stop if the dominance flag indicates that the new comer is dominated or if the equality is confirmed.

A particularity is that we anyway remove dominated solutions if we find some, and just stop in the middle if the new comer happened to be dominated/equal. If we use streams, because we generate a new list, stopping in the middle implies to discard any removal we may have done. If we assume that no removal should happen if we face a dominance or equality case, then it is fine to use streams.

# Basic Refinement

## Stream replacement

In order to exploit stream features, we first get the `Stream` instance from the list:
```java
stream = solutionList.stream();
```

Then we compute the dominance flag by using the `peek` method, which allows to do something to the element (or based on it) before to return it for the next step:
```java
final Object DOMINANCE = new Object();
stream = stream.peek(s -> s.setAttribute(DOMINANCE, dominanceComparator.compare(solution, s)));
```
Here we exploit the attributes of the solution to store this value, so we can exploit it later. This is one way to do, I show another one later.

Then, we filter out the dominated solutions:
```java
stream = stream.filter(s -> (Integer) s.getAttribute(DOMINANCE) != -1);
```
If we wanted to stop here, we could obtain the cleaned list by calling:
```java
solutionList = stream.collect(Collectors.toList());
```
Then we could add the new comer to have the complete list. The point is that we need to check that the new comer is not dominated or already in the list.

The dominance computation is already stored, but we still miss the equality computation, what we fix here:
```java
final Object EQUALITY = new Object();
stream = stream.peek(s -> s.setAttribute(EQUALITY, equalSolutions.compare(solution, s)));
```

From that point, we have all the data, and all what we need is to go ahead with the processing until the end or until we find a solution dominating or equal to the new comer:
```java
Iterator<S> streamIterator = stream.iterator();
List<S> newList = new LinkedList<>();
while (streamIterator.hasNext()) {
	S s = streamIterator.next();
	if ((Integer) s.getAttribute(DOMINANCE) == 1 || (Integer) s.getAttribute(EQUALITY) == 1) {
		return false;
	} else {
		newList.add(s);
	}
}
newList.add(solution);
solutionList = newList;
return true;
```

## Summary

By combining all the pieces together, and by exploiting the stream chaining, here is the complete code:
```java
final Object DOMINANCE = new Object();
final Object EQUALITY = new Object();
Iterator<S> streamIterator = solutionList.stream()
    .peek(s -> s.setAttribute(DOMINANCE, dominanceComparator.compare(solution, s)))
    .filter(s -> (Integer) s.getAttribute(DOMINANCE) != -1)
    .peek(s -> s.setAttribute(EQUALITY, equalSolutions.compare(solution, s) == 0))
    .iterator();

List<S> newList = new LinkedList<>();
while (streamIterator.hasNext()) {
  S s = streamIterator.next();
  boolean dominated = (Integer) s.getAttribute(DOMINANCE) == 1;
  boolean equal = (Integer) s.getAttribute(EQUALITY) == 1;
  if (dominated || equal) {
    return false;
  } else {
    newList.add(s);
  }
}
newList.add(solution);
solutionList = newList;
return true;
```
where the first half build the stream iterator without doing any computation yet, and the second half uses this iterator to compute one solution after the other, and stop or store the relevant solutions. If we did not stop, then the new comer was not dominated, so we add it and swap the list. Otherwise nothing changes.

## Discussion

### Alternative to attributes

One comment we can do is regarding the use of attributes. These attributes remain after the computation, which means that it takes place. A first optimization is to use static identifiers (`DOMINANCE` and `EQUALITY`) to ensure that they are overwritten at each evaluation. But still, we don't need them out of this method, so we should remove them somehow. Because attributes have no removal method and nothing ensure that an attribute set to `null` is removed (after all, `null` might be a relevant value for other cases), we cannot ensure such a removal without adding a `removeAttribute(id)`method.

If we want to avoid that, we could replace attributes by standalone objects (which can get garbage-collected after the computation) like `Pair<L, R>` (provided by `org.apache.commons.lang3.tuple`) although it would make it a bit more complicated because of two levels of encapsulation. To be able to do so, we need to replace `peek`, which impacts the element itself, by `map`, which replaces it by another one, and so changes the type of element for the next steps:
```java
Iterator<Pair<Pair<S, Integer>, Integer>> streamIterator = solutionList.stream()
    .map(s -> new Pair<S, Integer>(s, dominanceComparator.compare(solution, s)))
    .filter(p -> p.getSecond() != -1)
    .map(p -> new Pair<Pair<S, Integer>, Integer>(p, equalSolutions.compare(solution, p.getFirst())))
    .iterator();

List<S> newList = new LinkedList<>();
while (streamIterator.hasNext()) {
  Pair<Pair<S, Integer>, Integer> p = streamIterator.next();
  S s = p.getFirst().getFirst();
  boolean dominated = p.getFirst().getSecond() == 1;
  boolean equal = p.getSecond() == 1;
  if (dominated || equal) {
    return false;
  } else {
    newList.add(s);
  }
}
newList.add(solution);
solutionList = newList;
return true;
```
Sincerely, it is not clear at all to me when I read it. So I don't recommend it, to not say that I am against it.

### Stream as an arguable design choice

The advantage of this refined code is that, by using streams, we may exploit some parallelism (managed internally by the streams) over the list of solutions. But functionally speaking, it is the same process than before, so no striking improvement is made, and this potential parallelism is clearly mitigated by the fact that we create and feed a new list (instead of removing the dominated solutions from the original one), which involves more computation when we have more solutions to keep than to remove.

Moreover, we create additional objects through the streams. They might be light, but they are still there. And in the process we split the logics in two parts which are not straightforward: the first half calculates and processes, while the second half processes only. It would have been better to move all the processing to the stream, and just get the final result at the end, but if we do so we normally need to process the whole list, without stopping, which is clearly not interesting (unless we use exceptions, see in the next section).

## Summary

As a whole, considering how similar it is with the initial code (both in terms of structure and lines of code) and how clarity is decreased and processing improvements are uncertain, I would not recommend such a refinement.

# Exception-Based Refinement

## Idea

Instead of thinking about the whole process as a processing of the full list with potential breaks, another way to think about it is as a processing of the full list only, while breaks are exceptions in this process, like in [this post](http://stackoverflow.com/a/32566745).

## Implementation

First, we have to create an exception for our cases. Because both cases are dominance cases (the equal case is not a strict dominance but a dominance anyway), then we can create a single exception in the class:
```java
private static class DominatedException extends RuntimeException {}
```
Here, the fact that it is a `RuntimeException` is important, because these exceptions are not checked (you don't need to specify where they might be thrown). Checked exceptions (like the basic `Exception`) cannot be used here because lambdas have not been designed to throw exceptions by default. Only some methods, like `.forEach(lambda)`, seem to manage exceptions. If we want to use a checked exception, then we need to design our own stuff and it becomes heavy, so I preferred to use this alternative.

Once we have this exception available, we can use it in our code. This means that we can focus on processing by assuming that the new comer will never be dominated in any way (we still store the dominance value because we will need to use it several times at the end):
```java
final Object DOMINANCE = new Object();
solutionList = solutionList.stream()
    .peek(s -> s.setAttribute(DOMINANCE, dominanceComparator.compare(solution, s)))
    .filter(s -> (Integer) s.getAttribute(DOMINANCE) != -1)
    .collect(Collectors.toList());
solutionList.add(solution);
return true;
```

and then we add the exception management to stop when needed:
```java
try {
  final Object DOMINANCE = new Object();
  solutionList = solutionList.stream()
      .peek(s -> s.setAttribute(DOMINANCE, dominanceComparator.compare(solution, s)))
      .peek(s -> {if ((Integer) s.getAttribute(DOMINANCE) == 1) { throw new DominatedException(); }})
      .peek(s -> {if (equalSolutions.compare(solution, s) == 0) { throw new DominatedException(); }})
      .filter(s -> (Integer) s.getAttribute(DOMINANCE) != -1)
      .collect(Collectors.toList());
  solutionList.add(solution);
  return true;
} catch (DominatedException e) {
  return false;
}
```
Here I use 2 steps for readability, but we can also merge them in one `peek()`.

## Discussion

Here, I admit, the code is rather appealing. The main problem is that we use exceptions for a case which might be rather common, so some people may argue about performance gain here: managing exception implies an overload, so if the exception cases are common we might feel it on the performance. This is to be benchmarked to see exactly what happens.

We still have the same leaking concern with attributes (new attributes remain indefinitely), so we can use `Pair<L, R>` instead. But because it uses `map` instead of `peek`, which changes the type (`S` becomes `Pair<S, Integer>` with the dominance computation) we need an additional mapping at the end to come back to the original type (i.e. discard the dominance value), before to collect the new list:
```java
try {
  solutionList = solutionList.stream()
	  .peek(s -> {if (equalSolutions.compare(solution, s) == 0) { throw new DominatedException(); }})
	  .map(s -> new Pair<>(s, dominanceComparator.compare(solution, s))) // wrap the solution with the value
	  .peek(p -> {if (p.getSecond() == 1) { throw new DominatedException(); }})
	  .filter(p -> p.getSecond() != -1)
	  .map(p -> p.getFirst()) // get back the solution only
	  .collect(Collectors.toList());
   solutionList.add(solution);
   return true;
} catch (DominatedException e) {
  return false;
}
```

However, although it might seem appealing, we should not forget that we use a significantly different process here. If we apply the same principles on the original code, we can get this:
```java
try {
  Iterator<S> iterator = solutionList.iterator();
  while (iterator.hasNext()) {
    S listIndividual = iterator.next();
    int flag = dominanceComparator.compare(solution, listIndividual);
    if (flag == 1 || equalSolutions.compare(solution, listIndividual) == 0) {
      throw new DominatedException();
    } else if (flag == -1) {
     iterator.remove();
    }
  }
  solutionList.add(solution);
  return true;
} catch (DominatedException e) {
  return false;
}
```
which is not bad either... but which can be even further simplified in a straightforward one without exceptions:
```java
Iterator<S> iterator = solutionList.iterator();
while (iterator.hasNext()) {
  S listIndividual = iterator.next();
  int flag = dominanceComparator.compare(solution, listIndividual);
  if (flag == 1 || equalSolutions.compare(solution, listIndividual) == 0) {
    return false;
  } else if (flag == -1) {
   iterator.remove();
  }
}
solutionList.add(solution);
return true;
```
If I am not wrong in my code, this small piece is all what you need in `add(solution)` without using streams.

# Conclusion

So at the opposite of the basic refinement, using streams with exception might be nice, but it remains a matter of elegance more than performance. I would rather recommend to use the revised code just above rather than streams in this method. Streams seem more adapted for the creation of new entities rather than updates.

**Comment by ajnebro** [comment]
> Do you have some tests for this method? To check whether we miss something when we adapt it. If not, could you make some?

I have added a class for testing the class right now

**Comment by matthieu-vergne** [comment]
It seems that the attribute variants do not work with your tests because the mock for `IntegerSolution` does not manage attributes (it uses the setter without problems but the getter returns null).

**Comment by matthieu-vergne** [comment]
Both `Pair` variants work (I fixed a bit the first one). The very last revision (without streams) works as well.

**Comment by ajnebro** [comment]
I'm exploring this approach:
```java
  @Override
  public boolean add(S solution) {
    boolean hasTheSolutionBeenInserted = false;
    solutionList.removeIf(sol -> dominanceComparator.compare(solution, sol) == -1);
    //solutionList.removeIf(sol -> equalSolutions.compare(sol, solution) == 0) ;
    long dominantSolutions = solutionList.stream()
            .filter(sol -> dominanceComparator.compare(solution, sol) == 1)
            .count();
    if (dominantSolutions == 0) {
      solutionList.add(solution);
      hasTheSolutionBeenInserted = true;
    }

    return hasTheSolutionBeenInserted;
  }
```

The idea is to remove first all the dominated solutions by the incoming solution in the archive. The next step is to determine if the incoming solution is dominated by anyone of the archive. I'm using a filter, which is clearle inefficient. 

Still working on it ...

**Comment by matthieu-vergne** [comment]
Rather than `count()`, which enforces to check everything, you may prefer `findFirst()` or something like that, so the first which dominates the incoming is enough to ensure dominance.

**Comment by ajnebro** [comment]
Thanks. It seems to work, but I have to see how to manage the case of duplicated solutions (the commented line  ` //solutionList.removeIf(sol -> equalSolutions.compare(sol, solution) == 0) ;`)

**Comment by ajnebro** [comment]
This implementation passess all tests:

```java
  @Override
  public boolean add(S solution) {
    boolean hasTheSolutionBeenInserted = false;
    solutionList.removeIf(sol ->
            ((dominanceComparator.compare(solution, sol) == -1) ||
                    equalSolutions.compare(sol, solution) == 0)
    );
    S foundSolution = solutionList.stream()
            .filter(sol -> dominanceComparator.compare(solution, sol) == 1)
            .findFirst()
            .orElse(null);

    if (foundSolution == null) {
      solutionList.add(solution);
      hasTheSolutionBeenInserted = true;
    }

    return hasTheSolutionBeenInserted;
  }
```

**Comment by matthieu-vergne** [comment]
Did you check the returned value in your tests?

It seems to me that with this implementation, if the solution is already there, you first remove it with `removeIf()`, then obviously don't find it, and so add it and returns true, while initially you return false if it is already there (which is what is said by the Javadoc).

I think you should first check the equality, and return false if it finds one, otherwise remove dominated solutions and add the new one. Unless it is possible to have equal solutions in the list WITH dominated solutions?

**Comment by ajnebro** [comment]
> It seems to me that with this implementation, if the solution is already there, you first remove it with removeIf(), then obviously don't find it, and so add it and returns true, while initially you return false if it is already there (which is what is said by the Javadoc).

Hmmm, yes. If the solution is already in the archive it will be deleted and later inserted again. It doesn't seem a problem from the point of view of efficiency, but it sounds a bit strange.

> Unless it is possible to have equal solutions in the list WITH dominated solutions?

No, the archive should not have equal solutions. The definion of "equal" here is a bit tricky: two solutions are considered as equal if they have the same objective values.

**Comment by ajnebro** [comment]
> Did you check the returned value in your tests?

Yes. This is the unit test:
```java
public void shouldAddASolutionEqualsToOneAlreadyInTheArchiveDoNothing() {
    NonDominatedSolutionListArchive<IntegerSolution> archive ;
    archive = new NonDominatedSolutionListArchive<>() ;

    IntegerSolution solution = mock(IntegerSolution.class) ;
    when(solution.getNumberOfObjectives()).thenReturn(2) ;
    when(solution.getObjective(0)).thenReturn(1.0) ;
    when(solution.getObjective(1)).thenReturn(1.0) ;
    archive.add(solution) ;

    IntegerSolution solution2 = mock(IntegerSolution.class) ;
    when(solution2.getNumberOfObjectives()).thenReturn(2) ;
    when(solution2.getObjective(0)).thenReturn(2.0) ;
    when(solution2.getObjective(1)).thenReturn(0.0) ;
    archive.add(solution2) ;

    IntegerSolution equalSolution = mock(IntegerSolution.class) ;
    when(equalSolution.getNumberOfObjectives()).thenReturn(2) ;
    when(equalSolution.getObjective(0)).thenReturn(1.0) ;
    when(equalSolution.getObjective(1)).thenReturn(1.0) ;
    archive.add(equalSolution) ;

    assertEquals(2, archive.size()) ;
    assertTrue(archive.getSolutionList().contains(solution) ||
            archive.getSolutionList().contains(equalSolution)) ;
  }
```

but certainly I had to change the last assert. In the former version I checked only whether `solution` (the first one thas was added) was in the archive, and now the check is if the original or the new one is in the archive.

> I think you should first check the equality, and return false if it finds one, otherwise remove dominated solutions and add the new one.

Yes, but then the list should be traversed twice.

**Comment by matthieu-vergne** [comment]
> Yes, but then the list should be traversed twice.

With your code, you traverse it fully for the removal, then you traverse it partially with the find first. So the last one is the shortest, but you already traverse it fully with the first step. In total, you have between 1 and 2 traversals.

I suggest you to reverse the order, so you first make the search to know if it is dominated or equal (partial traversal), then skip the next step if it is, or make the full traversal for removing the dominated solutions. So you have between 0 and 2 traversals, which is more interesting.

Regarding the tests, it seems to me that your code does not satisfy your specification:
> **false** if the solution is dominated or **if an identical individual exists**.

Here, because you first remove it then add it again, you return `true` (it has been inserted) instead of `false` (it was already there from the start). But your test does not check the returned values. You never store them in the first place. You only check the content and size of the list.

**Comment by ajnebro** [comment]
> With your code, you traverse it fully for the removal, then you traverse it partially with the find first. So the last one is the shortest, but you already traverse it fully with the first step. In total, you have between 1 and 2 traversals.

Removing dominated solutions in the archive is a mandatory step, so this traversal cannot be skipped.

> Here, because you first remove it then add it again, you return true (it has been inserted) instead of false (it was already there from the start).

You are right. Time to think about this.

**Comment by matthieu-vergne** [comment]
> Removing dominated solutions in the archive is a mandatory step, so this traversal cannot be skipped.

Isn't it true that if you have an equal solution, then all dominated solutions have already been removed when this equal solution has been inserted?

Isn't it true that if the incoming solution S1 is dominated by a solution S2 already in the list, then all solutions dominated by S2 have already been removed, and so all solutions dominated by S1 too?

**Comment by ajnebro** [comment]
> Isn't it true that if you have an equal solution, then all dominated solutions have already been removed when this equal solution has been inserted?

It's true. Certainly, it doesn't have sense to remove dominated solutions if the incoming one is in the archive.

**Comment by ajnebro** [comment]
The next version of the `add()` method:
```java
  @Override
  public boolean add(S solution) {
    boolean hasTheSolutionBeenInserted = false;
    S solutionIsInTheArchive = solutionList.stream()
            .filter(sol -> equalSolutions.compare(sol, solution) == 0)
            .findFirst()
            .orElse(null);

    if (solutionIsInTheArchive == null) {
      solutionList.removeIf(sol -> dominanceComparator.compare(solution, sol) == -1);
      S foundSolution = solutionList.stream()
              .filter(sol -> dominanceComparator.compare(solution, sol) == 1)
              .findFirst()
              .orElse(null);

      if (foundSolution == null) {
        solutionList.add(solution);
        hasTheSolutionBeenInserted = true;
      }
    }
    return hasTheSolutionBeenInserted;
  }
```

I have modified the test cases to check the result of the `add()` operations. 

Things to revise:
* I'm not sure if filter is the best choice
* I don't like the `if (solutionIsInTheArchive == null)` comparison

**Comment by matthieu-vergne** [comment]
> Isn't it true that if the incoming solution S1 is dominated by a solution S2 already in the list, then all solutions dominated by S2 have already been removed, and so all solutions dominated by S1 too?

What about this one? Is it wrong? If it is correct, then you can also move the `foundSolution` step at the beginning and remerge it with `solutionIsInTheArchive`.

> I'm not sure if filter is the best choice

What do you dislike with filter? Given that you want to filter out the dominated ones, I don't see why you would expect something else.

> I don't like the `if (solutionIsInTheArchive == null)` comparison

Instead of `findFirst(predicate).orElse(null)` you can use `anyMatch(predicate)` which returns a boolean.
http://www.leveluplunch.com/java/examples/java-util-stream-find-match-example/

**Comment by ajnebro** [comment]
>> Isn't it true that if the incoming solution S1 is dominated by a solution S2 already in the list, then all solutions dominated by S2 have already been removed, and so all solutions dominated by S1 too?

> What about this one? Is it wrong? If it is correct, then you can also move the foundSolution step at the beginning and remerge it with solutionIsInTheArchive.

I'm not sure right now. I have to check that.

>> I'm not sure if filter is the best choice

>What do you dislike with filter? Given that you want to filter out the dominated ones, I don't see why you would expect something else.

My concern is about the use of the filter in 
```java
    Optional<S> solutionIsInTheArchive = solutionList.stream()
            .filter(sol -> equalSolutions.compare(sol, solution) == 0)
            .findAny();
```
but as it works, no problem on that. By the way, by using `Optional` the expression becomes
```java
    if (!solutionIsInTheArchive.isPresent()) {
```
which seems a bit better.

**Comment by ajnebro** [comment]
After the "first iteration" in this issue, the current approach is:

```java
  @Override
  public boolean add(S solution) {
    boolean hasTheSolutionBeenInserted = false;

    Optional<S> solutionIsInTheArchive = solutionList.stream()
            .filter(sol -> equalSolutions.compare(sol, solution) == 0)
            .findAny();

    if (!solutionIsInTheArchive.isPresent()) {
      solutionList.removeIf(sol -> dominanceComparator.compare(solution, sol) == -1);
      Optional<S> foundSolution = solutionList.stream()
              .filter(sol -> dominanceComparator.compare(solution, sol) == 1)
              .findAny() ;

      if (!foundSolution.isPresent()) {
        solutionList.add(solution);
        hasTheSolutionBeenInserted = true;
      }
    }
    return hasTheSolutionBeenInserted;
  }
```

Comparing it against the original code, I think that the we have got a clearly more readable code.

**Comment by matthieu-vergne** [comment]
I think that using match instead of filter+find, to get booleans, would be
even better.
http://www.concretepage.com/java/jdk-8/java-8-stream-allmatch-anymatch-nonematch-example

2016-11-17 7:59 GMT+09:00 Antonio J. Nebro <notifications@github.com>:

**Comment by ajnebro** [comment]
I agree :)

```java
  @Override
  public boolean add(S solution) {
    boolean hasTheSolutionBeenInserted = false;

    boolean solutionIsInTheArchive = solutionList.stream()
            .anyMatch(sol -> equalSolutions.compare(sol, solution) == 0);

    if (!solutionIsInTheArchive) {
      solutionList.removeIf(sol -> dominanceComparator.compare(solution, sol) == -1);
      boolean aSolutionHasBeenFound = solutionList.stream()
              .anyMatch(sol -> dominanceComparator.compare(solution, sol) == 1) ;

      if (!aSolutionHasBeenFound) {
        solutionList.add(solution);
        hasTheSolutionBeenInserted = true;
      }
    }
    return hasTheSolutionBeenInserted;
  }
```

**Comment by matthieu-vergne** [comment]
So if I am correct, the last thing to check is that:
> Isn't it true that if the incoming solution S1 is dominated by a solution S2 already in the list, then all solutions dominated by S2 have already been removed, and so all solutions dominated by S1 too?

which would allow to simplify again by merging both searches into one at the start.
