### ISSUE TITLE
R Indicator for three objectives

### ISSUE THREAD

**Issue by vinixnan** [jMetal/jMetal#184]
The class R2 is not working for more than two objectives
https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/qualityindicator/impl/R2.java

In jMetal 4.5 all objectives are considered if the user had passed the Pareto Front File. Now It is not working in this version.

**Comment by matthieu-vergne** [comment]
I guess a test should be implemented. I see the class also provides a lot of duplicated code which might be factored.

**Comment by matthieu-vergne** [comment]
If you cannot make a pull request, then I guess you should wait for @ajnebro or @Juanjdurillo to take care of it.

**Comment by ajnebro** [comment]
Hi @vinixnan 

I'm taking a look to the implementation of the R2 quality indicator in jMetal 5.0 and certainly I see that there is a partial implementation of the indicator. I didn't notice that because I never use R2 in my research work. 
 
I will put this issue in our TODO list for the next release. Unfortunately, I cannot devote time to it right now.

**Comment by Juanjdurillo** [comment]
Hi @vinixnan 
The R2 indicator should work now for more than 2 objectives. Unfortunately, I have no working test case for that. It would be great if you could test and let me know if there is any problem.

**Comment by matthieu-vergne** [comment]
And share the test through a pull request! {^_°}
