### ISSUE TITLE
How to create constrained permutation problem

### ISSUE THREAD

**Issue by CumaliTurkmenoglu** [jMetal/jMetal#218]
I want to create a new problem for multi constrained, multi objective, multi dimentional Knapsack problem which i want to implement it in permutation representation to control solutions to be feasible. 

`public class MO_MKP extends AbstractIntegerPermutationProblem implements ConstrainedProblem<PermutationSolution> `

Does not work however I can create a constrained problem such as Binh2 problem

`public class Binh2 extends AbstractDoubleProblem implements ConstrainedProblem<DoubleSolution> `

**Comment by matthieu-vergne** [comment]
`PermutationSolution` is a generic class (`PermutationSolution<T>`). You must specify the type of variables stored in the permutation solution. Otherwise it assumes the most generic (`PermutationSolution<Object>`) which conflicts with the fact that you extends `AbstractIntegerPermutationProblem`, which uses `PermutationSolution<Integer>`.

If you use instead `public class MO_MKP extends AbstractIntegerPermutationProblem implements ConstrainedProblem<PermutationSolution<Integer>>` then you can implement it.

**Comment by CumaliTurkmenoglu** [comment]
Thank you sir.
