### ISSUE TITLE
Discussion: switch algorithms to Callable<S> ?

### ISSUE THREAD

**Issue by Barbiero** [jMetal/jMetal#226]
Right now, the `Algorithm` interface implements `Runnable`, such that the implementations execute their code on the `run` method and, after that, we get the result of the algorithm via `getResult`.

That pattern - run and getResult - is pretty clearly a [Callable](http://devdocs.io/openjdk~8/java/util/concurrent/callable) pattern, minus the ability of throwing exceptions.

Callables are particularly useful since they match the use of `Executors`, and, to me, it feels like metaheuristics are perfect candidates for use with Executors and Callables - since we are performing expensive computations that we may want to get a result from at a later point in the program. 

For the sake of backwards compatibility it might be useful to implement a default run method on the main Algorithm interface such as
```java
default void run() {
    try {
        call();
    } catch(Exception ignored) { }
}
```
and call() implementations for classes would be something like
```java
R call() throws Exception {
    // do whatever the old run() methods used to do, maybe don't treat Exceptions if it makes sense
    return getResult();
}
```

The idea here is to use the correct tools for what the algorithms are supposed to do. This eases the use of `Executor`, `Future`s and other concurrency goodness from the standard library.

Thoughts?

**Comment by matthieu-vergne** [comment]
This is a discussion for me, but I don't have Internet now, so I will have to postpone for a few days. But be sure I'll come back to it as soon as I have the net.

Le 4 octobre 2017 21:55:48 GMT+02:00, Pedro Barbiero <notifications@github.com> a écrit :
>Right now, the `Algorithm` interface implements `Runnable`, such that
>the implementations execute their code on the `run` method and, after
>that, we get the result of the algorithm via `getResult`.
>
>That pattern - run and getResult - is pretty clearly a
>[Callable](http://devdocs.io/openjdk~8/java/util/concurrent/callable)
>pattern, minus the ability of throwing exceptions.
>
>Callables are particularly useful since they match the use of
>`Executors`, and, to me, it feels like metaheuristics are perfect
>candidates for use with Executors and Callables - since we are
>performing expensive computations that we may want to get a result from
>at a later point in the program. 
>
>For the sake of backwards compatibility it might be useful to implement
>a default run method on the main Algorithm interface such as
>```java
>default void run() {
>    try {
>        call();
>    } catch(Exception ignored) { }
>}
>```
>and call() implementations for classes would be something like
>```java
>R call() throws Exception {
>// do whatever the old run() methods used to do, maybe don't treat
>Exceptions if it makes sense
>    return getResult();
>}
>```
>
>The idea here is to use the correct tools for what the algorithms are
>supposed to do. This eases the use of `Executor`, `Future`s and other
>concurrency goodness from the standard library.
>
>Thoughts?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jMetal/jMetal/issues/226

-- 
Sent with my smartphone. Please excuse the brevity.

**Comment by ajnebro** [comment]
I have never used that interface, but after looking for its features I'm planning to adopt it.

**Comment by matthieu-vergne** [comment]
I did not reply because I don't have internet now, but we already discussed about Callable when refining the architecture of jMetal. We splitted the two to cover the algorithms which maintain a result that ,e can get at anytime. Thus, the run() might still be going, one can anyway ccll getResult() to get the current result, which then become a potential resource for stopping the algorithm.

Don't simply change the architecture. One can simply create such a callable by calling getResult() just after run(), so it is not a significant added value. You may add a default method which does exactly that, though. That would be retrocompatible.

But sincerely, I would like to see more a change like solve(problem), that would have more impact. Again, an old discussion.

Le 17 octobre 2017 07:36:27 GMT+02:00, "Antonio J. Nebro" <notifications@github.com> a écrit :
>I have never used that interface, but after looking for its features
>I'm planning to adopt it.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jMetal/jMetal/issues/226#issuecomment-337122922

-- 
Sent with my smartphone. Please excuse the brevity.

**Comment by matthieu-vergne** [comment]
Now that I am back on Internet, I can detail a bit more.

Initially, I quickly introduced the idea of using a `Callable` for the algorithm in https://github.com/jMetal/jMetal/issues/26#issuecomment-70522377, so again I am not against that. This can be done easily, without breaking anything, by adding `Callable<Result>` to the interfaces it extends and adding the default method:
```java
default Result call() {
  run();
  return getResult();
}
```

This way, anyone receives the feature.

Now, why do I put it aside? For 2 reasons.

First, the addition is purely cosmetic since we are now on Java 8, for which you can use lambdas to do the very same thing easily, like:
```java
new FutureTask<>(() -> { algorithm.run(); return algorithm.getResult(); });
```
so there is no significant need for such an addition.

Second, because there is a running discussion since the beginning of jMetal 5, about the definition of an algorithm as something independent from problems or not, which lead to discuss about whether we should have `run()` or `solve(problem)`. I confess that I am the one who blocked somehow the discussion in the early days (https://github.com/jMetal/jMetal/issues/54#issuecomment-76216426), since I was for the genericness of the former while the others were for the intuitiveness of the latter. But since sometime now I am pushing for it too (https://github.com/jMetal/jMetal/issues/55#issuecomment-201819872) since I figured that, in the long term, using the latter is a relevant step towards having problem-independent algorithms, thus letting the intuitiveness argument as the only relevant one. And that change would be significant, because it would have an impact on algorithms taking problems when calling this method rather than through their constructors, which is the current way jMetal goes now. But if we add `Callable` here, we just strengthen the `run()` perspective by adding a variant of it.

So I agree that, in the current state, your suggestion makes sense. But considering the history of the project and the long term view I have on it, I cannot support it.
