### ISSUE TITLE
How to change numberOfObjects?

### ISSUE THREAD

**Issue by dylanzx** [jMetal/jMetal#228]
I am a newer in jMetal. Now, I want to use ngsaiii algorithm and set the number of object to 5. And I run the NSGAIIIRunner class. what should I do next?

**Comment by matthieu-vergne** [comment]
If I remember well, you are supposed to make your own Runner class, based on your own needs. I will let @ajnebro describe how to use it, since I never use runners and directly instantiate the algorithm I need with the right parameters.

But really it depends on your needs, the ppint is not to just "run the algorithm". You have to tell it what problem to solve, and this problem is something you should provide by yourself.

I don't have the time to check now, but there is a repo jmetal-documentation too (not in this project, another project of the jmetal account). You may find explanations there.

**Comment by dylanzx** [comment]
I just run the given class NSGAIIIRunner.java to test problem WFG2, and the default configure are 2 objects and 6 variables. Now, my need is to change object from 2 to 5. Can you give a simple description? @ajnebro .

**Comment by ajnebro** [comment]
To use WFG2 with 5 objectives you can create the problem in this way:
```java
    problem = new WFG2(2,2,5) ;
```

**Comment by ajnebro** [comment]
About running NSGA-III with five objectives, just take into account that the population size is dependent on the number of objectives.
