### ISSUE TITLE
Update Sonar in Maven

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#235]
Just a suggestion: the `sonar-maven-plugin` in the POM is on version 2.2, but it has passed 3.3 already. I would suggest to update it.

By the way, I checked my fork of jMetal with it (I had to update the version to make it works, thus the suggestion), and here are the results:
https://sonarcloud.io/dashboard?id=org.uma.jmetal%3Ajmetal

I like it a lot. The 13.2% coverage is particularly alarming, by the way. If you know some people who want to participate but don't know where to start from, you may suggest them to look at this analysis to peek what they want from it and resolve it. {^_^}

**Comment by ajnebro** [comment]
I started using Sonar at the beginning of the project, but after receiving (and accepting) some contributions that didn't follow the rules I abandoned it. 

The alternatives were not to accept that contributions, refactor myself all the code, or accept them as was; I decided to adopt the last one. I thought in refactoring, but that would require to devote a lot ot time.

Anyway, I will take a look to this matter again, because it is sure that not all the issues raised by Sonar will be due to third-party code.

**Comment by matthieu-vergne** [comment]
The point of these tools are first of all for giving hints to improve. Then, once you are close to "all green", it becomes an incentive to remain there. I think changing the version is only worth for compatibility purpose for now (if someone run it, it should work). It does not mean that we have to keep running it.

I am the kind who like spend time on refactoring (just look at how I deal with warnings already), so it might become a good source.
