### ISSUE TITLE
How do I compare the value of the target function is good or bad, I do not understand how to compare the advantages and disadvantages of the value of an objective function in the non-dominated sorting

### ISSUE THREAD

**Issue by dawoshi** [jMetal/jMetal#239]
How do I compare the value of the target function is good or bad, I do not understand how to compare the advantages and disadvantages of the value of an objective function in the non-dominated sorting

NSGA2 assumes to have values to minimize ? For multi-objective If I want to know if a function's target value converges to a large or small one，What should I do ？

**Comment by dawoshi** [comment]
NSGA2 assumes to have values to minimize ? For multi-objective If I want to know if a function's target value converges to a large or small one，What should I do ？

**Comment by ajnebro** [comment]
Hi. I'm not sure to fully understand your questions, but anyway you can probably find the answer to them in the paper describing NSGA-II.

**Comment by matthieu-vergne** [comment]
Given that you are the one who should say how to compute the objective function, you should be the one who know what is a better value, independently of the algorithm. Then, if a better value for you is a bigger one, then for an algorithm which minimizes the values you need to provide the reverse for it to work correctly.

Does it answer your question? If not, then a better explanation would be required, especially:
- what you tried
- what is going wrong with what you tried
- what you expect instead

**Comment by dawoshi** [comment]
Is not their own definition of the function，it is a classic test function ZDT series, I was rewritten crossover class, to be changed to a generic function, which used to compare the pros and cons of the target value according to the function, so I want to obtain the target value of the definition function Bad method, because my class is generic, I want him to be based on different test functions can be compared to the merits of the target value of the method.

**Comment by matthieu-vergne** [comment]
For an algorithm minimizing the objective values, good values are lower values, and bad values are higher ones. For an algorithm maximising values, this is the reverse. That is the generic point. There might have additional rules depending on the algorithm, so you may also, as suggested earlier, look at the papers describing the algorithm you are interested in to understand better how these values are judged (good or bad).

Additionally, there is not always a known "best" or "worst" value: it might go towards infinite or be bounded, and in the latter case we might have no idea of the bound. So if you try to do something generic, you should consider that point too.

**Comment by dawoshi** [comment]
Thank you for your answer, I think in each test function class we should get a property, that is, this function is to seek the minimization problem or maximize the problem. I saw that part of the non-dominated sorting, which is dead-set for the minimization and maximization of functions.

**Comment by matthieu-vergne** [comment]
From an ontological point of view, I agree with you. But from a practical point of view, minimising or maximising is first of all a matter of convention. They are both strictly equivalent (one is minus the other), so it makes sense to not add complexity in the implementation just to manage both cases.

Fundamentally, we should not compare values with `a>b` or `a<b`, but with a more generic `Comparator`, especially applied to solutions themselves rather than specific values. If `Compare(s1, s2) > 0`, then `s1` is better than `s2`, and vice-versa. The point is that since Java 8 it is really easy to implement a `Comparator` through lambdas, so it makes sense now to ask for a comparator in arguments, but not much sense to make a specific class just for that I think. Unless you have specific ideas in mind.

**Comment by dawoshi** [comment]
Thank you very much for your answer, compare function in java really easy to use, but before we should know what kind of result is good, which result is not good, for different functions of their evaluation criteria are not the same, so We do need to get the good and bad standards defined for each function. Test function should have this property, and leak to the caller to get

**Comment by matthieu-vergne** [comment]
Then I disagree for 2 reasons:

First, if we do know what is good for each function separately, then it is obvious to find what is good for all of them together. In this case, finding the solution of the problem is trivial, and thus we have no need to use such algorithms. Theoretically, it would be easier, but in practice it would be totally irrelevant, because as soon as we get this information, using the algorithm becomes useless.

Second, what is good for a function can depend of the value of another function. In general, it is not a matter of knowing what is good for each function separately, but what are the good combinations. Again, we reach a state where we may have to know what is a good solution as a whole, not just a god value for a given function.

The fact that we do not know what is a good (or bad) solution/function value is precisely what makes these algorithms interesting: they don't need such an absolute information, only a relative one (given two solutions, which one is better), thus the use of comparisons.

If you speak only about testing, then yes it is interesting to have the best cases (and why not the worst ones). For that, you can run the algorithms several times and long enough, take the best results and use them in tests. And this is exactly what we do.

**Comment by dawoshi** [comment]
Thank you again for your answer, I would like to ask under JMetal have set up iterative generation? I only saw the number of evaluations, assessment of the number of what is the index, it is related to iterative generation?

**Comment by ajnebro** [comment]
I you use generational evolutionary algorithms such as NSGA-II, the number of generations is inmediatly obtained from the number of evaluations.

**Comment by dawoshi** [comment]
How to get the number from the evoluations  is the How many times generation? 
JMetal does have this interface? Hope to explain in detail.

**Comment by matthieu-vergne** [comment]
```java
@Override protected void initProgress() {
    evaluations = getMaxPopulationSize();
}

@Override protected void updateProgress() {
    evaluations += getMaxPopulationSize() ;
}
```
Evaluations = max population x number of generations
number of generations = evaluations / max population

**Comment by dawoshi** [comment]
Thank you very much

**Comment by dawoshi** [comment]
offspring= rankingAndCrowdingSelection.execute(offspring) ;
I would like to ask the size of this offspring,What is the processing power of rankingAndCrowding? I run my program,it Throws heap overflow.

**Comment by dawoshi** [comment]
I think it Need to optimize here, the segmentation after the parallel sort calculation, and then after the merger sort calculation

**Comment by matthieu-vergne** [comment]
This problem has nothing to do with this issue. Please open another issue
for that, and give details so we can reproduce it.

Le 16 déc. 2017 3:54 AM, "William" <notifications@github.com> a écrit :

I think it Need to optimize here, the segmentation after the parallel sort
calculation, and then after the merger sort calculation

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jMetal/jMetal/issues/239#issuecomment-352155788>, or mute
the thread

**Comment by dawoshi** [comment]
Ok,Thank you very much!

**Comment by matthieu-vergne** [comment]
Meanwhile, you can close this issue if you think we answered your question.
