### ISSUE TITLE
How to use this with eclipse?

### ISSUE THREAD

**Issue by AtreyaBanerjee** [jMetal/jMetal#244]
I downloaded the Jmetal jar file. I added it as external jar in the project but whenever I try to import it using import jmetal.XXXX , it shows error like "The import jmetal cannot be resolved".

**Comment by matthieu-vergne** [comment]
Because what you need to import are *classes*, located in *packages*. Not the JAR itself, which is only to be added in your build path.

If what I say does not make much sense to you, then you need to better grasp:
- how to add a JAR file to a project as a library in Eclipse,
- how to use classes provided by a JAR file.

These questions are out of the scope of jMetal, but they can be easily answered by asking your favorite search engine.

**Comment by IKVillanes** [comment]
I'm following the tutorial (jmetal4.5.userManual.pdf) jMetal + eclipse.
I downloaded this files:

- jmetal4.5.2.src.tar.gz (source code)
- jmetal4.5.2.jar.gz (binary jar file)

I have imported classes and jar files but I have this erro: 

> Archive for required library: 'C:/Tools/jmetal/jmetal4.5.2.jar' in project 'jMetal' cannot be read or is not a valid ZIP file

How can I fix it?

**Comment by ajnebro** [comment]
You only need the source code; just discard the jar file.

**Comment by matthieu-vergne** [comment]
It depends how you want to do it, but in any case it is not specific to jMetal.
So you will find all the information on the web.

If you want to add a dependency to jMetal in your own project, then you should add the JAR file, possibly associating the source zip to it.
You can look on the Web how to add a JAR to an Eclipse project by configuring its build path.
Then how to associate its source code.

If you already have the source code unzipped, then you can import it in your Eclipse.
Then you can configure your build path to depend on the jMetal project.
Again, look on the Web about adding a dependency to another project in Eclipse.
