### ISSUE TITLE
How to set the decision variable?

### ISSUE THREAD

**Issue by fsctz** [jMetal/jMetal#250]
If my decision variables are discrete, I need to choose between multiple non-contiguous ranges. For example, f = x^3 +2x + x^2.......      x=[1,10] || [15,20] || [30,40] ,How should I set it up？

**Comment by fsctz** [comment]
At the same time, how to ensure that each decision variable has different values？
Thank you!

**Comment by ajnebro** [comment]
Interesting question. Let me think about it.

By default, continuous variables in jMetal are defined by their lower and higher bounds, according to this interface:

``` java
public interface DoubleSolution extends Solution<Double> {
  Double getLowerBound(int index) ;
  Double getUpperBound(int index) ;
}
```

and whenever a new variable is created, a random number from the valid range of values is assigned to it.

**Comment by fsctz** [comment]
Thank you ! and how to ensure that each decision variable has different values？

**Comment by matthieu-vergne** [comment]
Regarding discrete values, you may use `IntegerSolution`.

Regarding the various ranges, you can concatenate them to have a single range.
You can then map the values, for example:
- 1-10 => 1-10
- 15-20 => 11-16
- 30-40 => 17-27

Then use a lower bound of 1 and upper bound of 27 to generate the solutions. Finally, you retrieve the original values by reverting this mapping in your objective function before computation. The variables are only genes, what they mean is irrelevant. As long as you can retrieve the data you need from them, feel free to play with them as you wish.

Of course, this is a hack due to the limitation of jMetal, not a feature. Despite a significant work done with the new version, jMetal still lacks abstraction to cover all the relevant cases properly. Further abstraction is still ongoing work.

**Comment by matthieu-vergne** [comment]
Regarding the constraint of having different values, the advice is rather similar: exploits the genes for that.

If the possibles values are finite and rather small, you may consider all the possible cases, map them to a single integer (so have 1 gene with many integer values), and retrieve the whole set of values from this single gene in your objective function.

For example:
- you need 3 values, each in {1, 2, 10}, but each different
- v1 is in {1, 2, 10}, so 3 possibilities
- v2 is in {1, 2, 10} - {v1}, so 2 possibilities
- v3 is in {1, 2, 10} - {v1, v2}, so 1 possibility

You have in total 3x2x1=6 possibilities. You use a single integer variable bounded from 1 to 6 and map back in the objective function:
1. v1=1, v2=2, v3=10
2. v1=1, v2=10, v3=2
3. v1=2, v2=1, v3=10
4. v1=2, v2=10, v3=2
5. v1=10, v2=1, v3=2
6. v1=10, v2=2, v3=1

Hope I got the point.
