### ISSUE TITLE
How to define equality constraints

### ISSUE THREAD

**Issue by suixinzhenguai** [jMetal/jMetal#280]
My optimization problem must satisfy two "equal constraint" as follows:

code here:

```
double[] constraint = new double[getNumberOfConstraints()];
double overallConstraintViolation = 0.0;
int violatedConstraints = 0;

// These two constraint variables must be equal to 0
constraint[0] = VMConstraints;		// This constraint variable must be equal to 0
constraint[1] = NumofConflictTasks;		// This constraint variable must also be equal to 0
for (int i = 0; i < getNumberOfConstraints(); i++) 
{
	if (constraint[i] != 0.0) // If constraint[i] is not equal to 0, then the constraint is violated
	{
		overallConstraintViolation+=constraint[i];
		violatedConstraints++;
	}
}
overallConstraintViolationDegree.setAttribute(solution, overallConstraintViolation);
numberOfViolatedConstraints.setAttribute(solution, violatedConstraints);
```

Here is my question:
**Question 1:** I don't know whether the expression of "equivalent constraint" is correct. If it is wrong, then how can I express "equal constraint", could you give me an example?
**Question 2:** I have read ajnebro's response to the question "How to set constraints" (https://github.com/jMetal/jMetal/issues/241).
Ajnebro means we must formulate the constraints in as unequalities of type 0 < V ?
So should I make the following changes:

code here:
```
constraint[0] = VMConstraints * -1;		// Multiply the constraint variable by -1
constraint[1] = NumofConflictTasks * -1;		// Multiply the constraint variable by -1
for (int i = 0; i < getNumberOfConstraints(); i++) 
{
	if (constraint[i] < 0.0) // If constraint[i] less than 0, then the constraint is violated
	{
		overallConstraintViolation+=constraint[i];
		violatedConstraints++;
	}
}
```
Whether the equality constraint can only be expressed like this, is there any other method?

**Question 3:** If I use the expression of the first equation constraint, there will be many violations of the constraint results in my optimization results, and the degree of violation is very serious, but changed to the second, the number and degree of violations will be much better. However, there are still some violations of the constraint.
At the same time, no matter how large the number of iterations (such as 20,000 generations), there are still violations of constraints, and it is difficult to converge. Doesn't the optimization process help me to eliminate the consequences of those violations?

**Comment by suixinzhenguai** [comment]
Add  description: the value of the constraint will only be 0, or a positive integer 。

**Comment by matthieu-vergne** [comment]
**Question 1:** If your concern is about how to name the property you want to speak about, try first to formulate it in a mathematical way, so we can avoid subjective interpretations.

**Question 2:** Indeed, the semantic is that it is a constraint violation when it is `< 0`. If you use  `!= 0`, then you change the semantic, because positive values are also constraint violations. If it is what you want, then you need to align it such that the algorithm interpret it correctly. So you need to represent any value different than 0 as a negative number. You can do that for example by taking `- Math.abs(constraint[i])`:
```java
constraint[0] = VMConstraints * -1;		// Multiply the constraint variable by -1
constraint[1] = NumofConflictTasks * -1;		// Multiply the constraint variable by -1
for (int i = 0; i < getNumberOfConstraints(); i++) 
{
	float value = - Math.abs(constraint[i])
	if (value < 0.0) // If constraint[i] less than 0, then the constraint is violated
	{
		overallConstraintViolation+=value;
		violatedConstraints++;
	}
}
```
Such a solution means that a value of 3 violates the constraint as much than a value of -3. If it is not what you want, then you need a more complex formula.

**Question 3:** It does not help you to *eliminate* them, but to *minimize* them. If there is perfect solutions (such that the overall violation is 0), then you have a *chance* to reach them, but no *guarantee*. Of course, if there is no such solution, then it will never find one. If there is a perfect solution but you never reach it, then it means the operators (random, mutation, etc.) do not fit well enough to cover your solution space effectively/efficiently. And vice-versa, if the shape of your space is simple but you never find a perfect solution, then it probably means there is no perfect solution for the constraints you want.

**Comment by suixinzhenguai** [comment]
Thank you for your detailed explanation, it is very helpful for my understanding.
