### ISSUE TITLE
Checklist for the new jMetal version

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#31]
I have said sometimes that we are not in a hurry for finishing the new jMetal version. However, jMetal is the tool I use in most of my research works and now we are facing in our group a complex optimization problem and a colleague has started to work with the 4.5 version. As this involves a lot of work to do, it seems to me a waste of time to use the old version when this is going to be replaced by the new one sooner or later. So, I'm affraid that I'm starting to need the new jMetal preferably sooner.

The final design is not finished of course, but we have made a lot of progress:
- The core package contains four interfaces instead of seven classes.
- The enconding package has been simplified, removing abstractions such as `Variable`, `SolutionType`, `XReal`, `XInt`.
- The use of generics has made the code more flexible and robust, reducing the need of writing runtime checks. As a consequence, the implementation of problems and operators require less code.

The point is that I would like to ensure that the design is ok to us, given that it should last years, so we should avoid to make drastic changes frequently. Up to now there are furthermore some open issues that are mandatory to be closed, in my opinion:
1. The runner/settings to configure and run the algorithms, either standalone or in experiments.
2. We have not stablished a common criterion to comment the code in a uniform way.
3. Unit tests are missing.
4. I would like to reconsider the random number generation (evaluating whether using http://commons.apache.org/proper/commons-math/userguide/random.html or not).

On the other hand, there are some issues that perhaps could be delayed, because they can be orthogonal to the current code. I'm thinking in the algorithm measures, which is something very attractive to me but perhaps it could be posponed for further releases, given that at a first glance we can provide the existing algorithms and later versions endowed with the possibility of using push and pull measures.

**Comment by inaciomdrs** [comment]
Hello everybody. I'm Inácio, from Brazil. Since 2012 I have used massively JMetal in research I do over here, and having a look in new architecture of framework, I see how big improvements were done. Thanks dudes for removing classes such as Variable and SolutionType! New model employed simplifies so much stuffs, especially for retrieving values from a Solution.

And YES, MarsenneTwister PRNG was a very rightful choice! Java(TM)'s one is very untrustful, not being a good deal use it.

Two curiosities I have:

1) Which are the uses of <code>Point</code> interface?
2) Looking at GitHub issues, I saw that last messages date back from Oct. 2014, and then I ask: how are nowadays jMetal new version development? Is it intended to be released sooner, or it will last more couple of months until its official release?

Last but not least, thank you so much for have developed this incredible framework. Even the older versions made development and programming IA/EA an "easy" and "fast" task, perhaps defining a "standard" for it.

Greetings,
Inácio Medeiros
UFRN - IMD - Brazil

**Comment by matthieu-vergne** [comment]
Regarding the `Point` interface, I let Antonio answer. I will be for sure more reliable than me for this task.

Regarding the deployment, so far we are still on a snapshot version, so no stable release so far. I don't know if Antonio has planned a deadline for the proper stable release. Personally, I don't like deadlines, so it is more a matter of "there is still some tasks to achieve before a stable release". From my point of view, stable release will be reasonable when the measures/parameters will be finalized (i.e. main interfaces and basic implementations done + used in existing algorithms), because it seems to me the center of the generalisation, which is the main purpose of my contribution.

So far, measures were implemented, but I did not check how much Antonio used them. Parameters are also somehow ready on my experimental branch, I should just finish some refinements and the documentation. Then, the whole point is to use them. I am also implementing a generic experiment to stress that parameters and measures are designed well-enough, but I have not finished and I am quite busy now. At least I should make the pull request for the parameters so that Antonio can look at and integrate them (although the request is not necessary for that).

So from my point of view, the main work remaining is the integration part, in order to use the new, generic stuff inside the already implemented algorithm. But this is at the condition that Antonio actually want to have them before to release, which I think is not mandatory (they can be added without breaking anything, so they can come within a 5.1 or 5.2 version). Also, not waiting for them would give us the possibility to make it progressive by adding them one after the other in consecutive versions 5.x, making old stuff progressively obsolete (leading to warnings in IDEs without the need to actually change implementations), before to actually remove them for a version 6, where all the old stuff will be actually replaced in order to exploit at best the new features. The version 5 would act like a progressive transition to the new architecture, giving the possibility for previous users to follow better the improvements.

At least, this is how I see it.

**Comment by ajnebro** [comment]
Hi Inácio.
  Thanks for your comments. I'm glad to know that our framework is useful to other researchers. In fact, that's the idea ;).
  
 As Matthieu has commented, the new release is not ready yet and we have not fixed any deadline. There are some key features that we want to finish, such as the measures. Currently I'm working in adding the quality indicators (the Point and the Front classes are needed for implementing the WFG version of the hypervolume), some algorithms are still missing (AbYSS, MOCell, SPEA2), and we will have to change completely the part of experimental studies. 

  Anyway, we are planning to use the new version soon in our research work, so we hope to have a first release with the new architecture in a few months.


Antonio

**Comment by inaciomdrs** [comment]
Thanks for response, Antonio and Matthieu. Really, it's in an advanced stage, sooner will be complete.
Just another question (a curiosity): Does Juan J. Durillo still participate of this project?

**Comment by matthieu-vergne** [comment]
Seems so: https://github.com/jMetal/jMetal/graphs/contributors
His last direct commit on the master branch is from December, so not that long ago. Then there could have more recent merges or commits in other branches. I did not check.

**Comment by inaciomdrs** [comment]
I see.. thanks for the answer, Matthieu.
