### ISSUE TITLE
builder

### ISSUE THREAD

**Issue by momah** [jMetal/jMetal#318]
Maybe my question is the result of my ignorance in the subject.
I'm working with IntegerProblem and I'm testing several algorithms with JMetal.
I have noticed that some algorithms or their Builders declared for generic solutions that I can use for IntegerSolution
`public MOCellBuilder(Problem<S> problem, ...`
But others are already declared for specific solutions (DoubleSolution)
`public IBEABuilder(Problem<DoubleSolution> problem) {`
That means that some algorithms are not compatible with all types of solutions (Integer, Double,Binary,..)? or the specific Builders must be implemented by the user?

**Comment by matthieu-vergne** [comment]
JMetal 5 achieves some advances in terms of generalization, but there is still room for improvements. Whether or not builders are concerned is however an open question to me, since I didn't dig in this matter. Maybe it could be generalized.

Any pull request in that direction would be greatly appreciated.

**Comment by ajnebro** [comment]
Some algorithms are designed to solve a given class of optimization problems. For example, PSO and differential evolution are typically applied to continous problems. On the contrary, evolutionary algorithms can be used with any kind of problems whenever crossover and mutation operators are properly defined.

**Comment by momah** [comment]
Thank you.
If we can contribute something we will do it with pleasure.
