### ISSUE TITLE
Any use of DoubleBinary ?

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#342]
@ajnebro 
My Eclipse does not find any implementation of `DoubleBinaryProblem`. It also seems that the `DoubleBinarySolution` interface and its sole implementation `DefaultDoubleBinarySolution` are only used by the implementation itself.

Do you have any relevant problems & algorithms to store in the project for the double-binary solutions? Or should we consider to deprecate it for future removal?

**Comment by ajnebro** [comment]
My opinion about this issue is to deprecate for future removal. As you mention, that class is not used in the framework and it is only included to ilustrate an example of mixing two encodings. As I'm now rethinking everything related to the solution representations, feel free to mark it as deprecated.

**Comment by matthieu-vergne** [comment]
There is still the `IntegerDouble` case, which is used by `NMMin2`.

I will do that deprecation in a future commit, since I have other modifications before.
