### ISSUE TITLE
The Copy constructor of 'DefaultIntegerDoubleSolution' has a bug

### ISSUE THREAD

**Issue by tungchiminh** [jMetal/jMetal#366]
Hi,
In the Copy constructor body, the member variables 'numberOfIntegerVariables' and 'numberOfDoubleVariables'  must also be initialized.

```
  /** Copy constructor */
  public DefaultIntegerDoubleSolution(DefaultIntegerDoubleSolution solution) {
    super(solution.problem);

    /**************the following two lines need to be added**********************/
    numberOfIntegerVariables = problem.getNumberOfIntegerVariables();
    numberOfDoubleVariables = problem.getNumberOfDoubleVariables();

    ...
    ...
  }
```

**Comment by matthieu-vergne** [comment]
Indeed it seems so.
Either do that, or replace `super(solution.problem)` by `this(solution.problem)`.
Maybe this was the intention, but mistakenly copy-pasted the `super`.
@ajnebro should be able to fix it quickly.

However, I would recommend to add a test that confirm the issue.
It would save from future regressions and it may show other issues.

**Comment by ajnebro** [comment]
As Matthieu points out, the bug is due to the use of `super()` instead of `this()`. I will fix it.

Anyway, I'm working on a different approach to implement solutions containing different encodings.  The idea I'm thinking of is to define a solution as a container of other solutions. In the case of one mixing integer and double variables, the interface will look like this:
```java
public interface IntegerDoubleSolution extends Solution<Solution<?>> {
  IntegerSolution getIntegerSolution() ;
  DoubleSolution getDoubleSolution() ;
}
```
and a `DefaultIntegerDoubleSolution` class will be similar to this code:
```java
public class DefaultIntegerDoubleSolution extends AbstractSolution<Solution<?>>
    implements IntegerDoubleSolution {

  /** Constructor */
  public DefaultIntegerDoubleSolution(
      List<Pair<Integer, Integer>> integerBounds,
      List<Pair<Double, Double>> doubleBounds,
      int numberOfObjectives,
      int numberOfConstraints) {
    super(2, numberOfObjectives, numberOfConstraints);

    setVariable(
        0, new DefaultIntegerSolution(integerBounds, numberOfObjectives, numberOfConstraints));
    setVariable(
        1, new DefaultDoubleSolution(doubleBounds, numberOfObjectives, numberOfConstraints));
  }

  @Override
  public IntegerSolution getIntegerSolution() {
    return (IntegerSolution) getVariable(0);
  }

  @Override
  public DoubleSolution getDoubleSolution() {
    return (DoubleSolution) getVariable(1);
  }

  @Override
  public DefaultIntegerDoubleSolution copy() {
    return new DefaultIntegerDoubleSolution(this);
  }
}
```

This way, we could apply existing crossover and mutation operators to the integer and double solutions included in the container solution.

I'm just working on a proof of concept, to determine the potential advantages and drawbacks of this approach.

**Comment by matthieu-vergne** [comment]
Maybe you can open a dedicated issue to discuss this matter and share the branch you are working on. I may have comments to share, but it is clearly out of the scope of this issue.

**Comment by ajnebro** [comment]
Fixed.
