### ISSUE TITLE
Using JMetal 5 for string generation.

### ISSUE THREAD

**Issue by JackLieu** [jMetal/jMetal#389]
Hi! I am trying to use JMetal to generate strings for multiobjective and single objective problems [https://www.geeksforgeeks.org/genetic-algorithms/] but no such example is provided in the documentation. Can you provide any information related to this?

**Comment by matthieu-vergne** [comment]
What do you mean by "generating strings"?

# The whole solution is a `String`

You can use an algorithm with `BinarySolution`. It builds on the custom class `BinarySet` which extends the standard `BitSet`.

You can easily go back and forth between `String` and the standard `BitSet`:
```java
// String -> BitSet
String inputStr = "my string";
BitSet bitSet = BinarySet.valueOf(inputStr.getBytes());

// BitSet -> String
String outputStr = new String(bitSet.toByteArray());
```

Although `BinarySet` does not facilitate the creation of a specific instance, you can use the `BitSet` features to do it:
```java
// String -> BinarySet
String inputStr = "my string";
BitSet bitSet = BinarySet.valueOf(inputStr.getBytes());
BinarySet binarySet = new BinarySet(bitSet.length()); // create binary set with right size
binarySet.or(bitSet); // feed the binary set with the bits of the string

// BinarySet -> String
String outputStr = new String(binarySet.toByteArray());
```

As far as I see, we only have the MOCHC algorithm which works directly with `BinarySolution`.

Beside that, you can work with more generic algorithms which could accept a `Solution<String>`. In that case, look at the next section and just consider that your solution as a single (string) variable.

# Your solution contains multiple strings

I am not aware of any specific implementation to cover this use case, so you have to go with your own solutions. You can use the `AbstractSolution` to facilitate the implementation. For the algorithms, you should look at generic algorithms which accept a `Solution<String>`.

I am not familiar with each algorithm but, as far as I trust the generics (and I know I shouldn't), there is a bunch of algorithms accepting any kind of solution:
```
org.uma.jmetal.algorithm.multiobjective.cdg.AbstractCDG
org.uma.jmetal.algorithm.multiobjective.espea.ESPEA
org.uma.jmetal.algorithm.multiobjective.fame.FAME
org.uma.jmetal.algorithm.multiobjective.gwasfga.GWASFGA
org.uma.jmetal.algorithm.multiobjective.ibea.IBEA
org.uma.jmetal.algorithm.multiobjective.mocell.MOCell
org.uma.jmetal.algorithm.multiobjective.moead.AbstractMOEAD
org.uma.jmetal.algorithm.multiobjective.mombi.AbstractMOMBI
org.uma.jmetal.algorithm.multiobjective.mombi.MOMBI
org.uma.jmetal.algorithm.multiobjective.mombi.MOMBI2
org.uma.jmetal.algorithm.multiobjective.nsgaii.NSGAII
org.uma.jmetal.algorithm.multiobjective.nsgaiii.NSGAIII
org.uma.jmetal.algorithm.multiobjective.paes.PAES
org.uma.jmetal.algorithm.multiobjective.pesa2.PESA2
org.uma.jmetal.algorithm.multiobjective.randomsearch.RandomSearch
org.uma.jmetal.algorithm.multiobjective.rnsgaii.RNSGAII
org.uma.jmetal.algorithm.multiobjective.smsemoa.SMSEMOA
org.uma.jmetal.algorithm.multiobjective.spea2.SPEA2
org.uma.jmetal.algorithm.multiobjective.wasfga.WASFGA
org.uma.jmetal.algorithm.singleobjective.geneticalgorithm.GenerationalGeneticAlgorithm
org.uma.jmetal.algorithm.singleobjective.geneticalgorithm.SteadyStateGeneticAlgorithm
```

However, I remember some algorithms casting solution variables into a specific types, which breaks the purpose of the genericity (which is why we cannot trust the generics here). So some algorithms might be actually unsuited.

**Comment by JackLieu** [comment]
I don't know if this answers your question but by generating strings i mean using an algorithms lets suppose the NSGAII, to generate various readable sentences like "Hi! My name is Jack." and measure the no of generations and other derivable factors to reach this.

On the other hand, thanks for the guidance.

**Comment by ajnebro** [comment]
I have developed a solution to cope with this issue, which is included in the  `feature/stringSolution` branch. @JackLieu, feel free to take a look to the example included in class [`GenerationalGeneticAlgorithmStringMatchingRunner`](https://github.com/jMetal/jMetal/blob/feature/stringSolution/jmetal-example/src/main/java/org/uma/jmetal/example/singleobjective/GenerationalGeneticAlgorithmStringMatchingRunner.java).

The solution consists in a new encoding (class [`CharSequenceSolution`](https://github.com/jMetal/jMetal/blob/feature/stringSolution/jmetal-core/src/main/java/org/uma/jmetal/solution/sequencesolution/impl/CharSequenceSolution.java)) and a mutation operator (class [`CharSequenceRandomMutation`](https://github.com/jMetal/jMetal/blob/feature/stringSolution/jmetal-core/src/main/java/org/uma/jmetal/operator/mutation/impl/CharSequenceRandomMutation.java)). The problem to be optimized is defined in class [`StringMatching`](https://github.com/jMetal/jMetal/blob/feature/stringSolution/jmetal-problem/src/main/java/org/uma/jmetal/problem/singleobjective/StringMatching.java).

**Comment by matthieu-vergne** [comment]
Dealing with the "readable sentence" aspect is a natural language processing (NLP) problem, though. So it is out of our scope. You would need to identify words, recombine sentences by taking care of how to cut/reorganize/rephrase to remain meaningful, stuff like that. It is possible, but you would need specialized operators for that.
