### ISSUE TITLE
How to use Integer and Double variables in one problem?

### ISSUE THREAD

**Issue by thhart** [jMetal/jMetal#415]
I am new to this framework, maybe a silly question, but how can I mix variables of different types or alternatively limit Doubles to Integer evaluation steps?

**Comment by matthieu-vergne** [comment]
I am not sure to understand the need here.

If you want to use heterogeneous solutions, like some variables are numbers and other variables are objects, it is not really supported, although not technically impossible. You would need a solution of object variables but we don't have implemented operators for that. So it would need extra effort on your side. In the specific case of doubles and integers, you may just use double solutions, and store your integer variables as doubles too. You may need to cast into integer before to do your calculation, though.

If you want to use bounded doubles, but apply integer boundaries, then you just need to be consistent: since you try to bound doubles, just cast your integer into double before to use it as a boundary.

If it is not helpful, please provide more details to better understand your case.

**Comment by thhart** [comment]
I  want to use JMetal to optimize a complex non-linear problem which depends on multiple variables the problem is constructed as this as JMetal can evaluate for a minimum to optimize for. All the variables have different boundaries and some of them are limited to discrete values only (Integers).
Casting is not this problem, the problem is the algorithm should not evaluate unnecessary variable values to test for. I have the idea to cache the evaluation result for these pseudo Integers, however this is not the optimal solution of course.

The problem is like this: I perform special image transformations like Sauvola thresholding and other filters to prepare images for optimal further processing. The image  set is very broad and I am looking for an optimal parameter space (variables) to get the smallest error possible, Some of these parameters are Integers.

**Comment by matthieu-vergne** [comment]
I remember we have an IntegerDoubleSolution:
https://github.com/jMetal/jMetal/tree/master/jmetal-core/src/main/java/org/uma/jmetal/solution/integerdoublesolution

As well as a CompositeSolution:
https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/solution/compositesolution/CompositeSolution.java

Not sure how to use them, though. @ajnebro would probably be more helpful than me on that matter. And since they are more "hacks" than proper solution designs, they may disappear in future versions. But you may try them to see if they fit your use case.

If you use them, please provide feedback, so we can have more intel about heterogeneous solutions and better design them.

**Comment by ajnebro** [comment]
As @matthieu-vergne points out, you can try the `CompositeSolution` class. You can find a full example here: https://github.com/jMetal/jMetal/blob/master/jmetal-experimental/src/main/java/org/uma/jmetal/experimental/component/example/multiobjective/nsgaii/NSGAIIWith3DChartExample.java

In this program, the NSGA-II algorithm is configured to solve a problem having integer and real variables (https://github.com/jMetal/jMetal/blob/master/jmetal-problem/src/main/java/org/uma/jmetal/problem/multiobjective/MixedIntegerDoubleProblem.java).

**Comment by thhart** [comment]
Thanks for the tips and fast feedback, I will check out the examples and try to give feedback as possible.
I have a little further question related to this: How intelligent is an algorithm in the choice of a variable variety? Are all variables treated with the same step amount or are variables favored against others depending on their learned influence?

**Comment by ajnebro** [comment]
The example using the mixed representation is only intended to show how these kinds of encodings can be defined and used. The problem is merely academic, and the operators applied (selection, crossover, and mutation) are the most commonly applied. 

In your case, using these operators could be a way to have a first set of solutions that could be used as a reference starting point. However, given the features that you mention about your problem, you should probably need to define specific operators to find accurate solutions.
