### ISSUE TITLE
IDE Configuration

### ISSUE THREAD

**Issue by matthieu-vergne** [jMetal/jMetal#47]
It woud be nice to write somewhere how to configure the IDE to have the same formatting than you. In particular, in Eclipse you can use CTRL+F to wrap the lines, align the indentations, etc. following a given strategy, and you can configure this strategy in the parameters of Eclipse. You can also provide the header of the files (e.g. license info) so that it is automatically added at the creation of the file, and many more. It would be nice to have this information somewhere so that all contributors can use the same layout. Otherwise, when you modify the file of someone else and use CTRL+F, it changes everything if you do not use the same layout, which makes ugly commits with more formatting stuff than productive modifications.

**Comment by ajnebro** [comment]
I agree. I'm using IntelliJIdea most of the time, but I go back to Eclipse sometimes. In both IDEs I use the Google style guide: http://google-styleguide.googlecode.com/svn/trunk/javaguide.html

About the license, we use LGPL instead of GPL because I was suggested to do so by people working in companies who wanted to use jMetal in their software. Until recently, we included the license information at the beginning of each class in this way:

```java```
//  AdaptiveGrid.java
//
//  Author:
//       Antonio J. Nebro <antonio@lcc.uma.es>
//       Juan J. Durillo <durillo@lcc.uma.es>
//
//  Copyright (c) 2011 Antonio J. Nebro, Juan J. Durillo
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ```

but now I'm merely using something like this:
```java
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Lesser General Public License for more details.
//
//  You should have received a copy of the GNU Lesser General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package org.uma.jmetal.util.point;

/**
 * Interface representing a point
 *
 * @author Antonio J. Nebro
 * @version 1.0
 */
public interface Point {
  public int getNumberOfDimensions();
  public double[] getValues() ;
  public double getDimensionValue(int index) ;
  public void setDimensionValue(int index, double value) ;
}
```

**Comment by matthieu-vergne** [comment]
Would you mind exporting your style and sharing it here? The link is dead, and although I could find the style on the Web it does not do everything the same. For instance, semicolons re not preceded by a white space. I have tried to configure it, but it is a bit tricky to obtain the same thing.

**Comment by ajnebro** [comment]
I use IntelliJ Idea, configured with the Google Java Style guide (try this [link](https://github.com/google/styleguide/blob/gh-pages/intellij-java-google-style.xml)), but using a tab size and indent of 2 spaces. No special other special settings is changed.
