### ISSUE TITLE
Making a prototype of algorithm using measures

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#49]
I have added an NSGAIIM.java class to test the use of measures.

**Comment by ajnebro** [comment]
Using the `CountingMeasure` class to be used to count iterations would lead to this code:
```java
public class NSGAIIM extends NSGAII {
  private CountingMeasure iterations ;

  /**
   * Constructor
   */
  public NSGAIIM(Problem problem, int maxIterations, int populationSize,
      CrossoverOperator crossoverOperator, MutationOperator mutationOperator,
      SelectionOperator selectionOperator, SolutionListEvaluator evaluator) {
    super(problem, maxIterations, populationSize, crossoverOperator, mutationOperator, selectionOperator, evaluator) ;

  }

  @Override protected void initProgress() {
    iterations = new CountingMeasure(1) ;
  }

  @Override protected void updateProgress() {
    iterations.increment();
  }

  @Override protected boolean isStoppingConditionReached() {
    return iterations.get() >= maxIterations;
  }
```
This usage seems clear enough: it does not imply any significant modification of the algorithm and it is used in a natural way.

**Comment by matthieu-vergne** [comment]
The pull usage, you already do it here:
```java
 @Override protected boolean isStoppingConditionReached() {
    return iterations.get() >= maxIterations;
  }
```
If you don't need to react to any increment of the number of iteration, then there is no reason to see any registration to this measure **inside** the algorithm. The whole point now would be to make it available from outside. The simplest way is to make the member `public`, but you limit its access to the ones who know that they are dealing with the `NSGAIIM` implementation. If you want to make it generic, you need to implement the `Measurable` interface, thus adding for instance:
```java
public MeasureManager getMeasureManager() {
	SimpleMeasureManager manager = new SimpleMeasureManager();
	manager.setMeasure("number of iterations", iterations);
	return manager;
}
```
A priori, one should expect that an algorithm *is* `Measurable` (otherwise you just make it so by wrapping it, pull measures can be built automatically from getters for instance) so you can always request the `MeasureManager` without knowing which algorithm you are dealing with. Because your measure is instantiated at the initialization of the algorithm, it does not exists before you have actually started the first run, which is something I do not recommend. This way, you cannot have a manager that you instantiate once for all, because the instance is renewed at each run. So you have to build it on the fly (like shown) or in the init method once you have instantiated all your measures (and probably this would be smarter than what I did here).

If you want to build the manager once for all and avoid any struggle out of the running, then you should instantiate your measure from the constructor and use the init method to reset it to zero (I have added reset methods in pull request #50).
