### ISSUE TITLE
jMetal UML diagrams

### ISSUE THREAD

**Issue by ajnebro** [jMetal/jMetal#54]
First version of the core class diagram of the new jMetal release:

![architecturecoreclassdiagram](https://cloud.githubusercontent.com/assets/1889196/6389177/fd244d96-bda1-11e4-9036-0dea4a1ee632.png)

**Comment by ajnebro** [comment]
First version of the core class diagram of the new jMetal release:
https://github.com/jMetal/jMetal/blob/master/figures/ArchitectureCoreClassDiagram.png

**Comment by matthieu-vergne** [comment]
Maybe you should rename your generics, because single letters are not really informative:
- `Algorithm<R>` > `Algorithm<Result>`
- `Operator<V,R>` > `Operator<Input,Output>`
- `Solution<T>` > `Solution<Type>`
- `Problem<S>` > `Problem<Solution>`
- `ConstrainedProblem<S>` > `ConstrainedProblem<Solution>`

Another point is regarding the relations:
- `Algorithm` manages `Solution`: while a human can understand that an algorithm aims at producing and providing solutions, the model does not show how solutions and algorithms relates (excepted this "manages" relations which does not have any concrete code related to it).
- `Algorithm` solves `Problem`: for me, an algorithm does not solve a problem. An algorithm provides a solution which solves a problem. This view is supported by the fact the the problem evaluate and create solutions, but has nothing in common with the algorithm (as the algorithm has nothing in common with the problem).
- `Algorithm` uses `Operator`: if it is the case, then you should have something in the algorithm for that, like `getOperator(Object):Operator`.

In brief, these relations should have some concrete representation in the code. Maybe it is done by some intermediary components, but then these components should appear. If the point is to have a simplified view of the model (I am thinking about the paper in which you could prefer to have small, easy to read pieces of the full diagram), then I would expect to have another diagram for each of these relations.

Did you think about using tools to retrieve the UML diagram from the code directly? I am convinced there is some free ones out there that you could use to get a full diagram, that you can then simplify to remove irrelevant details. You can look there for instance: http://stackoverflow.com/questions/6167266/generate-uml-class-diagram-from-java-project

**Comment by ajnebro** [comment]
Juanjo Durillo told me the same about renaming generics. I'm working on it.

Yes, the idea is to have a simple model to include it in the paper; a full class diagram will be very large. Then, other diagrams detailing subclasses of `Solution`, `Operator`, etc. can be added.

For me, an algorithm exists to solve a problem. The point is that the current `Algorithm` interface:

```java
public interface Algorithm<R> extends Runnable, Serializable {

  /** Runs the algorithm */
  public void run() ;
  public R getResult() ;
}
```
does not contain any reference to any problem.

Then, perhaps it could be modified in this way:

```java
public interface Algorithm<R> extends Runnable, Serializable {

  /** Runs the algorithm */
  public void solve(Problem problem) ;
  public R getResult() ;
}
```
A `solve(Problem)` method is more intuitive that a generic `run()` one.


I have wasted a lot of time reviewing reverse enginering tools for obtaining UML designs from code with no success. Finally, I'm doing the designs manually with ... PowerPoint.

**Comment by inaciomdrs** [comment]
Regarding to a UML tool for drawing diagrams, I suggest Dia [1, 2], it's very simple, easy-to-use, and supports not only UML, but another types of diagrams.

[1] http://dia-installer.de/shapes/UML/index.html.en
[2] http://portableapps.com/apps/office/dia_portable

**Comment by inaciomdrs** [comment]
By the way, it's a good using of <code>solve(Problem)</code>. It makes that method more "fluent" and flexible, in the sense that you can use same algorithm configuration for different problems, instead of "reinistatiate it" every time you have a new Problem.

**Comment by matthieu-vergne** [comment]
If you make the diagram manually, you could also use Dia, as @inaciomdrs mentionned it. I also use it.

> For me, an algorithm exists to solve a problem. [...] A `solve(Problem)` method is more intuitive that a generic `run()` one.

The algorithm/problem dependence, as it is relating central concepts, should be deeply thought, because it has a significant impact on all the rest. So I will open an issue on that, because for me there is a central problem here. It does not mean that my opinion is better than yours, but at least we should be aligned on the main concepts to understand each other.

> By the way, it's a good using of solve(Problem). It makes that method more "fluent" and flexible, in the sense that you can use same algorithm configuration for different problems, instead of "reinistatiate it" every time you have a new Problem.

Not at all. If it does not depend on a given problem, then you can use it for whatever problem. If it depends, then you are not that free, because you have to satisfy the constraints of the dependency. And putting a direct dependence with `solve(Problem)` is a strong dependency. Generalization is not a matter of context-specific practicality, but well grounded conceptualization. Things which are apparently practical are important as hints and examples, like what you put in tests, but they are not the ones which should lead to decisions, so what you put in code. Otherwise you generally overlook some significant details and hurt the generalization.

I will open an issue regarding these concepts, so we can discuss deeper their relation.

**Comment by ajnebro** [comment]
I agree in that the dependence algorithm/problem must be thought carefully.

**Comment by ajnebro** [comment]
From the point of view of a typical jMetal user, the framework is used to solve optimization problems with metaheuristics, so the there is a logical connection between algorithm and problem, but it is true that the problems have no relationships with the algorithms.

In the current implementation such relationship is not present, as an algorithm only has a `run()` method, so it could do anything apart from optimizing a problem. However, the purpose of jMetal is not to provide a generic framework for algorithms, but for metahuristic algorithms, and the purpose of these techniques is to optimize problems.

**Comment by matthieu-vergne** [comment]
If I agree on the relationship, then I have to disagree on the terminology. I would not be surprised that this is the point, this is why I plan to open a dedicated discussion where we can share our conceptualization. I assume it is not the goal of the current issue, this is why I don't go more in details on that. So please wait for me to clearly pose my concerns in another issue before to discuss.

**Comment by ajnebro** [comment]
Yes, it is clearly better to open a new issue.
