### ISSUE TITLE
Problem with MultithreadedSolutionListEvaluator

### ISSUE THREAD

**Issue by javierferrer** [jMetal/jMetal#86]
I have noticed that the threads used by the "MultithreadedSolutionListEvaluator" do not close after the main algorithm execution is finished. I have solved this issue by adding the statement "evaluator.shutdown()" in the "run()" method of a particular implementation of the NSGAII. For example, in the generationalGA the visibility of the evaluator is private, so I could not fix this problem in the same way. 
I guess you can find the most appropiate class to add the evaluator shutdown call to minimize modifications in the source code.

Thank you,
Javier Ferrer

**Comment by matthieu-vergne** [comment]
Considering that [MultithreadedSolutionListEvaluator](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/evaluator/impl/MultithreadedSolutionListEvaluator.java) relies on [MultithreadedEvaluator](https://github.com/jMetal/jMetal/blob/master/jmetal-core/src/main/java/org/uma/jmetal/util/parallel/impl/MultithreadedEvaluator.java) to compute the tasks in parallel, and considering that there is proper start and stop methods for the second which are properly called in the first, I assume that the problem would occur in two cases:
- the tasks added are not finished (can be in infinite loop)
- the stop method of MultithreadedSolutionListEvaluator (shutdown()) is not properly called where this evaluator is used

For the first case, the stopping have to be forced, which could be done by using `executor.shutdownNow()` instead of a passive `executor.shutdown()` in `MultithreadedEvaluator.stop()`. This makes sense if the stopping method is supposed to be called when no task at all need to be run anymore.

The second point can be fixed broadly by overriding the `finalize()` method of `MultithreadedEvaluator` to call `executor.shutdown()`. Indeed, if the object is finalized, it means that nobody will be able to add any other task, so you can just shutdown the executor and it will finish what it has to do before to close everything. Calling `shutdownNow()` here would be probably a mistake, because one can create the instance of the evaluator, add all the tasks at the start and then just forget about it (don't keep any reference on it), so it willl be candidate for finalization. Yet, the tasks need to be run until they are properly finished.

The hardest case is the combination of the two, because here you never explicitly call the stopping method, so you have no confirmation that it is supposed to be stopped, and even if the evaluator is finalized, it only means that we lost all references on it, not that the tasks it has launched are not needed anymore.

One way I see would be to enforce somehow the call to stop() if the call to start() has been made. For instance by introducing in the finalize method a way to notify the user that the finalization has been made without the stop method to be called. I think that exceptions are not managed in `finalize()`, never tried it though, but one could imagine to log an error. For instance:
```
private void finalize() {
  if (problem != null && !executor.isShutdown()) {
    // Notify the user about a wrong use of the evaluator
    log.error(this+" has been started, but also finalized before to be properly stopped!");
    // Attempt to recover
    executor.shutdown();
  } else {
    // everything has been done properly
  }
}
```

Another way, safer but less controlled, would be to make *daemon* threads. They do not block the JVM from stopping (i.e. daemon threads are forced to be stopped when all non-daemon threads are stopped). This can be achieved by initializing the executor with the right `ThreadFactory`:
```
Executors.newFixedThreadPool(numberOfThreads, new ThreadFactory() {
	
	@Override
	public Thread newThread(Runnable runnable) {
		Thread thread = new Thread(runnable);
		thread.setDaemon(true);
		return thread;
	}
});
```
This way, no task that you would run would block the JVM, although infinite tasks would still run until the JVM is stopped. If you use daemon threads, you could still use the `finalize()` shown above, but just display a warning. Probably this combination would be the best for a practical purpose.

**Comment by ajnebro** [comment]
Javier,
  I have added getters to the genetic algorithm builder, so the evaluator is now accesible. Just take a look to the `ParallelGenerationalGeneticAlgorithmBuilder` class: https://github.com/jMetal/jMetal/blob/master/jmetal-exec/src/main/java/org/uma/jmetal/runner/singleobjective/ParallelGenerationalGeneticAlgorithmRunner.java
 
  The code now is:

```java
 GeneticAlgorithmBuilder<BinarySolution> builder = new GeneticAlgorithmBuilder<BinarySolution>(
        problem, crossoverOperator, mutationOperator)
        .setPopulationSize(100)
        .setMaxEvaluations(25000)
        .setSelectionOperator(selectionOperator)
        .setSolutionListEvaluator(new MultithreadedSolutionListEvaluator<BinarySolution>(numberOfCores, problem)) ;

    algorithm = builder.build() ;

    AlgorithmRunner algorithmRunner = new AlgorithmRunner.Executor(algorithm)
        .execute() ;

    builder.getEvaluator().shutdown();
```
I have just deployed a new release (5.0-Beta-34), so you can update the dependence in your pom.xml file.

**Comment by javierferrer** [comment]
Thank you very much!
Javier
